package view;

import javax.swing.JOptionPane;
import model.Usuario;

public class CadastroCliente extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroCliente.class.getName());
    private int idEnderecoSelecionado = 0;
    private javax.swing.DefaultListModel<String> listaModelTelefones = new javax.swing.DefaultListModel<>();
    private java.util.List<model.Telefone> telefonesParaSalvar = new java.util.ArrayList<>();
    private Usuario usuarioLogado;

    public CadastroCliente(Usuario usuario) {
        initComponents();
        this.usuarioLogado = usuario;
        listTelefones.setModel(listaModelTelefones);
        limparCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnlimparCCliente = new javax.swing.JButton();
        btnCadastrarCliente = new javax.swing.JButton();
        btnVoltarTPrincipal = new javax.swing.JButton();
        rbClienteVip = new javax.swing.JRadioButton();
        lblCliente = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        lblCpfCliente = new javax.swing.JLabel();
        txtCpfCliente = new javax.swing.JTextField();
        lblEmailCliente = new javax.swing.JLabel();
        txtEmailCliente = new javax.swing.JTextField();
        lblDtNascCliente = new javax.swing.JLabel();
        txtDataNascCliente = new javax.swing.JTextField();
        lblDtCadCliente = new javax.swing.JLabel();
        txtDtCadCliente = new javax.swing.JTextField();
        lblTelCliente = new javax.swing.JLabel();
        txtTelCliente = new javax.swing.JTextField();
        lblObservacoes = new javax.swing.JLabel();
        txpObsCliente = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        cbTipoTel = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDdd = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        listTelefones = new javax.swing.JList<>();
        btnAdicionarTel = new javax.swing.JButton();
        btnAdicionarEndereco = new javax.swing.JButton();
        btnListagemCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Cliente");

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        lblTitulo.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        lblTitulo.setText("Instituto da Beleza");

        btnlimparCCliente.setBackground(new java.awt.Color(255, 255, 0));
        btnlimparCCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnlimparCCliente.setText("Limpar");
        btnlimparCCliente.setToolTipText("Limpa o formulário");
        btnlimparCCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnlimparCCliente.addActionListener(this::btnlimparCClienteActionPerformed);

        btnCadastrarCliente.setBackground(new java.awt.Color(255, 255, 0));
        btnCadastrarCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCadastrarCliente.setText("Cadastrar");
        btnCadastrarCliente.setToolTipText("Cadastro de Cliente");
        btnCadastrarCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCadastrarCliente.addActionListener(this::btnCadastrarClienteActionPerformed);

        btnVoltarTPrincipal.setBackground(new java.awt.Color(255, 255, 0));
        btnVoltarTPrincipal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVoltarTPrincipal.setText("Voltar");
        btnVoltarTPrincipal.setToolTipText("Volta para a tela principal");
        btnVoltarTPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVoltarTPrincipal.addActionListener(this::btnVoltarTPrincipalActionPerformed);

        rbClienteVip.setText("Cliente Vip");
        rbClienteVip.setToolTipText("Marque quando o cliente for assíduo");

        lblCliente.setLabelFor(txtCliente);
        lblCliente.setText("Nome:");

        txtCliente.setToolTipText("Escreva o nome completo");

        lblCpfCliente.setLabelFor(txtCpfCliente);
        lblCpfCliente.setText("CPF:");

        txtCpfCliente.setToolTipText("Escreva o CPF");

        lblEmailCliente.setLabelFor(txtEmailCliente);
        lblEmailCliente.setText("E-mail");

        txtEmailCliente.setToolTipText("Email não obrigatório");

        lblDtNascCliente.setLabelFor(txtDataNascCliente);
        lblDtNascCliente.setText("Data de Nascimento:");

        txtDataNascCliente.setToolTipText("Data válida com ano XXXX");

        lblDtCadCliente.setLabelFor(txtDtCadCliente);
        lblDtCadCliente.setText("Data de Cadastro:");

        txtDtCadCliente.setToolTipText("Data de hoje, ano XXXX");

        lblTelCliente.setLabelFor(txtTelCliente);
        lblTelCliente.setText("Telefone:");

        txtTelCliente.setToolTipText("Telefone ou celular com DDD");

        lblObservacoes.setLabelFor(txpObsCliente);
        lblObservacoes.setText("Observações:");

        txpObsCliente.setForeground(new java.awt.Color(153, 153, 153));
        txpObsCliente.setToolTipText("Escreva as preferências de produtos e serviços");

        cbTipoTel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o tipo", "celular", "trabalho", "casa" }));
        jScrollPane2.setViewportView(cbTipoTel);

        jLabel1.setText("DDD:");

        jScrollPane3.setViewportView(txtDdd);

        jScrollPane4.setViewportView(listTelefones);

        btnAdicionarTel.setText("Salvar telefone cadastrado");
        btnAdicionarTel.addActionListener(this::btnAdicionarTelActionPerformed);

        btnAdicionarEndereco.setText("Adicionar Endereço");
        btnAdicionarEndereco.addActionListener(this::btnAdicionarEnderecoActionPerformed);

        btnListagemCliente.setBackground(new java.awt.Color(255, 255, 0));
        btnListagemCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnListagemCliente.setText("Listagem");
        btnListagemCliente.setToolTipText("Volta para a tela principal");
        btnListagemCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnListagemCliente.addActionListener(this::btnListagemClienteActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(31, 31, 31))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblEmailCliente)
                                .addGap(18, 18, 18)
                                .addComponent(txtEmailCliente)
                                .addGap(467, 467, 467))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblDtNascCliente)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDataNascCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblDtCadCliente)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDtCadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(31, 31, 31))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdicionarEndereco)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblObservacoes)
                                .addGap(18, 18, 18)
                                .addComponent(txpObsCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCadastrarCliente)
                                .addGap(51, 51, 51)
                                .addComponent(btnlimparCCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(btnVoltarTPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(btnListagemCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTelCliente)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAdicionarTel, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCliente)
                                    .addComponent(lblCpfCliente))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(85, 85, 85)
                                        .addComponent(rbClienteVip))))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbClienteVip))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpfCliente)
                    .addComponent(txtCpfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEmailCliente)
                    .addComponent(txtEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDtNascCliente)
                            .addComponent(txtDataNascCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDtCadCliente)
                            .addComponent(txtDtCadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelCliente)
                            .addComponent(txtTelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAdicionarTel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdicionarEndereco)
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblObservacoes)
                    .addComponent(txpObsCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarCliente)
                    .addComponent(btnlimparCCliente)
                    .addComponent(btnVoltarTPrincipal)
                    .addComponent(btnListagemCliente))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarTPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarTPrincipalActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarTPrincipalActionPerformed

    private void btnCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarClienteActionPerformed
        if (txtCliente.getText().trim().isEmpty() || txtCpfCliente.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nome e CPF são campos obrigatórios!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {

            model.Cliente cli = new model.Cliente();
            cli.setNomeCliente(txtCliente.getText().trim());
            cli.setCpf(txtCpfCliente.getText().trim());

            java.text.SimpleDateFormat formatoData = new java.text.SimpleDateFormat("dd/MM/yyyy");
            formatoData.setLenient(false);

            try {
                String dtNascTexto = txtDataNascCliente.getText().trim().replace("/", "").trim();
                if (!dtNascTexto.isEmpty()) {
                    java.util.Date dataUtil = formatoData.parse(txtDataNascCliente.getText().trim());
                    cli.setDataNascimento(dataUtil);
                } else {
                    cli.setDataNascimento(null);
                }
            } catch (java.text.ParseException ex) {
                JOptionPane.showMessageDialog(this, "Data de Nascimento inválida! Use o formato dd/MM/yyyy.", "Erro de Validação", JOptionPane.WARNING_MESSAGE);
                txtDataNascCliente.requestFocus();
                return;
            }

            cli.setEmail(txtEmailCliente.getText().trim());
            cli.setObservacao(txpObsCliente.getText().trim());
            cli.setAtivo(rbClienteVip.isSelected());
            cli.setFkEndereco(this.idEnderecoSelecionado);

            model.ClienteDAO dao = new model.ClienteDAO();
            dao.Adicionar(cli, telefonesParaSalvar);

            JOptionPane.showMessageDialog(this, "Cliente cadastrado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            limparCampos();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao cadastrar: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCadastrarClienteActionPerformed

    private void btnlimparCClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimparCClienteActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnlimparCClienteActionPerformed

    private void btnAdicionarTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarTelActionPerformed

        if (txtDdd.getText().trim().isEmpty() || txtTelCliente.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha o DDD e o Número do telefone antes de adicionar!", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {

            model.Telefone novoTel = new model.Telefone();

            String tipo = cbTipoTel.getSelectedItem().toString().trim().toLowerCase();
            novoTel.setTelefoneTipo(tipo);
            novoTel.setDdd(txtDdd.getText().trim());
            novoTel.setTelefone(txtTelCliente.getText().trim());

            if (this.telefonesParaSalvar == null) {
                this.telefonesParaSalvar = new java.util.ArrayList<>();
            }
            this.telefonesParaSalvar.add(novoTel);

            javax.swing.DefaultListModel<String> modelList;
            if (listTelefones.getModel() instanceof javax.swing.DefaultListModel) {
                modelList = (javax.swing.DefaultListModel<String>) listTelefones.getModel();
            } else {
                modelList = new javax.swing.DefaultListModel<>();
                listTelefones.setModel(modelList);
            }

            String linhaVisual = "(" + novoTel.getDdd() + ") " + novoTel.getTelefone() + " [" + novoTel.getTelefoneTipo() + "]";
            modelList.addElement(linhaVisual);

            txtDdd.setText("");
            txtTelCliente.setText("");
            cbTipoTel.setSelectedIndex(0);
            txtTelCliente.requestFocus();

            System.out.println("Telefone adicionado à lista. Total atual: " + this.telefonesParaSalvar.size());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao adicionar telefone na lista: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnAdicionarTelActionPerformed

    private void btnAdicionarEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarEnderecoActionPerformed
        TelaEndereco telaEnd = new TelaEndereco(this, true);
        telaEnd.setLocationRelativeTo(this);
        telaEnd.setVisible(true);
        this.idEnderecoSelecionado = telaEnd.getIdEnderecoGerado();
        if (this.idEnderecoSelecionado > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Endereço vinculado! ID: " + this.idEnderecoSelecionado);
        }
    }//GEN-LAST:event_btnAdicionarEnderecoActionPerformed

    private void btnListagemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListagemClienteActionPerformed
        ListagemClientes telaListagem = new ListagemClientes(this.usuarioLogado);
        telaListagem.setLocationRelativeTo(null);
        telaListagem.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnListagemClienteActionPerformed

    private void limparCampos() {
        txtCliente.setText("");
        txtCpfCliente.setText("");
        txtDataNascCliente.setText("");
        txtEmailCliente.setText("");
        txtTelCliente.setText("");
        txtDdd.setText("");
        cbTipoTel.setSelectedIndex(0);
        txtDtCadCliente.setText("");
        txpObsCliente.setText("");
        rbClienteVip.setSelected(true);
        this.idEnderecoSelecionado = 0;
        this.listaModelTelefones.clear();
        this.telefonesParaSalvar.clear();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastroCliente(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarEndereco;
    private javax.swing.JButton btnAdicionarTel;
    private javax.swing.JButton btnCadastrarCliente;
    private javax.swing.JButton btnListagemCliente;
    private javax.swing.JButton btnVoltarTPrincipal;
    private javax.swing.JButton btnlimparCCliente;
    private javax.swing.JComboBox<String> cbTipoTel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblCpfCliente;
    private javax.swing.JLabel lblDtCadCliente;
    private javax.swing.JLabel lblDtNascCliente;
    private javax.swing.JLabel lblEmailCliente;
    private javax.swing.JLabel lblObservacoes;
    private javax.swing.JLabel lblTelCliente;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JList<String> listTelefones;
    private javax.swing.JRadioButton rbClienteVip;
    private javax.swing.JTextPane txpObsCliente;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtCpfCliente;
    private javax.swing.JTextField txtDataNascCliente;
    private javax.swing.JTextField txtDdd;
    private javax.swing.JTextField txtDtCadCliente;
    private javax.swing.JTextField txtEmailCliente;
    private javax.swing.JTextField txtTelCliente;
    // End of variables declaration//GEN-END:variables
}
