package view;

import javax.swing.JOptionPane;

public class CadastroProduto extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroProduto.class.getName());
    private model.Usuario usuarioLogado;

    /**
     * Creates new form CadastroProduto
     */
    public CadastroProduto(model.Usuario usuario) {
        this.usuarioLogado = usuario;
        initComponents();

        carregarFornecedoresNoCombo();
        limparCampos();
    }

    private void limparCampos() {
        txtProduto.setText("");
        txtQdeProduto.setText("0");
        txtPrecoProduto.setText("0.00");
        txtDtValidade.setText("");
        txpObsFuncionario.setText("");
        cbCategoria.setSelectedIndex(0);
        cbFornecedorAtivo.setSelectedIndex(0);
        rbProdAtivo.setSelected(true);
    }

    private void carregarFornecedoresNoCombo() {
        try {

            model.FornecedorDAO fDAO = new model.FornecedorDAO();
            java.util.List<model.Fornecedor> lista = fDAO.listarTodos();

            cbFornecedorAtivo.removeAllItems();
            cbFornecedorAtivo.addItem("Selecione o fornecedor:");

            for (model.Fornecedor f : lista) {
                cbFornecedorAtivo.addItem(f.getIdFornecedor() + " - " + f.getRazaoSocial());
            }
        } catch (Exception e) {

            cbFornecedorAtivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Selecione o fornecedor:"}));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnlimparCProduto = new javax.swing.JButton();
        btnCadastrarProduto = new javax.swing.JButton();
        btnVoltarTPrincipal = new javax.swing.JButton();
        rbProdAtivo = new javax.swing.JRadioButton();
        lblProduto = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        lblQdeProduto = new javax.swing.JLabel();
        txtQdeProduto = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        lblPrecoProduto = new javax.swing.JLabel();
        txtPrecoProduto = new javax.swing.JTextField();
        lblDtValidade = new javax.swing.JLabel();
        txtDtValidade = new javax.swing.JTextField();
        lblObsFuncionario = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txpObsFuncionario = new javax.swing.JTextPane();
        lblCategoria = new javax.swing.JLabel();
        lblFornecedor = new javax.swing.JLabel();
        cbCategoria = new javax.swing.JComboBox<>();
        cbFornecedorAtivo = new javax.swing.JComboBox<>();
        btnListagemProduto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro Produto");

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro Produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        lblTitulo.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        lblTitulo.setText("Instituto da Beleza");

        btnlimparCProduto.setBackground(new java.awt.Color(255, 255, 0));
        btnlimparCProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnlimparCProduto.setText("Limpar");
        btnlimparCProduto.setToolTipText("Limpa o formulário");
        btnlimparCProduto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnlimparCProduto.addActionListener(this::btnlimparCProdutoActionPerformed);

        btnCadastrarProduto.setBackground(new java.awt.Color(255, 255, 0));
        btnCadastrarProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCadastrarProduto.setText("Cadastrar");
        btnCadastrarProduto.setToolTipText("Cadastro de Produtos");
        btnCadastrarProduto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCadastrarProduto.addActionListener(this::btnCadastrarProdutoActionPerformed);

        btnVoltarTPrincipal.setBackground(new java.awt.Color(255, 255, 0));
        btnVoltarTPrincipal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVoltarTPrincipal.setText("Voltar");
        btnVoltarTPrincipal.setToolTipText("Volta para a tela principal");
        btnVoltarTPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVoltarTPrincipal.addActionListener(this::btnVoltarTPrincipalActionPerformed);

        rbProdAtivo.setText("Produto Ativo");
        rbProdAtivo.setToolTipText("Marque quando o cliente for assíduo");

        lblProduto.setLabelFor(txtProduto);
        lblProduto.setText("Produto:");

        txtProduto.setToolTipText("Escreva o nome completo");

        lblQdeProduto.setLabelFor(txtQdeProduto);
        lblQdeProduto.setText("Quantidade:");
        lblQdeProduto.setToolTipText("");

        txtQdeProduto.setToolTipText("Quantidade de caixas, frascos etc");

        lblTotal.setText("Total:");

        lblPrecoProduto.setLabelFor(txtPrecoProduto);
        lblPrecoProduto.setText("Preço:");

        txtPrecoProduto.setToolTipText("Valor unitário do produto");

        lblDtValidade.setLabelFor(txtDtValidade);
        lblDtValidade.setText("Data de Validade:");

        txtDtValidade.setToolTipText("Data de validade, ano XXXX");

        lblObsFuncionario.setText("Descrição:");

        txpObsFuncionario.setForeground(new java.awt.Color(153, 153, 153));
        txpObsFuncionario.setToolTipText("Escreva sobre qualidade e aparência do produto");
        jScrollPane1.setViewportView(txpObsFuncionario);

        lblCategoria.setLabelFor(cbCategoria);
        lblCategoria.setText("Categoria:");

        lblFornecedor.setLabelFor(cbFornecedorAtivo);
        lblFornecedor.setText("Fornecedor:");

        cbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a categoria:", "Material de limpeza", "Manicure", "Cabelo", "Depilação", "Maquiagem", "Equipamentos" }));

        cbFornecedorAtivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o fornecedor", "fornecedor A", "fornecedor B", "fornecedor C" }));
        cbFornecedorAtivo.setToolTipText("Selecione um modelo de horário de trabalho");

        btnListagemProduto.setBackground(new java.awt.Color(255, 255, 0));
        btnListagemProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnListagemProduto.setText("Listagem");
        btnListagemProduto.setToolTipText("Volta para a tela principal");
        btnListagemProduto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnListagemProduto.addActionListener(this::btnListagemProdutoActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblFornecedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbFornecedorAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblQdeProduto)
                                    .addComponent(lblTotal)
                                    .addComponent(lblPrecoProduto)
                                    .addComponent(lblObsFuncionario)
                                    .addComponent(btnCadastrarProduto))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addComponent(btnlimparCProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnVoltarTPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(128, 128, 128))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtQdeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPrecoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCategoria)
                            .addComponent(lblProduto))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblDtValidade)
                                .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDtValidade, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbProdAtivo)
                            .addComponent(lblTitulo)))
                    .addComponent(btnListagemProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProduto)
                    .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCategoria)
                                    .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(lblFornecedor))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(cbFornecedorAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(17, 17, 17)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblQdeProduto)
                                            .addComponent(txtQdeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(27, 27, 27)
                                        .addComponent(lblTotal)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPrecoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblDtValidade)
                                            .addComponent(txtDtValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(lblPrecoProduto)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rbProdAtivo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblObsFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarProduto)
                    .addComponent(btnlimparCProduto)
                    .addComponent(btnVoltarTPrincipal)
                    .addComponent(btnListagemProduto))
                .addGap(50, 50, 50))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarProdutoActionPerformed

        if (txtProduto.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "O nome do produto é obrigatório!", "Aviso", JOptionPane.WARNING_MESSAGE);
            txtProduto.requestFocus();
            return;
        }

        try {

            model.Produto prod = new model.Produto();
            prod.setNomeProduto(txtProduto.getText().trim());
            prod.setDescricao(txpObsFuncionario.getText().trim());
            prod.setAtivo(rbProdAtivo.isSelected());

            try {
                prod.setEstoqueAtual(Integer.parseInt(txtQdeProduto.getText().trim()));
            } catch (NumberFormatException e) {
                prod.setEstoqueAtual(0);
            }

            try {
                prod.setPrecoVenda(Double.parseDouble(txtPrecoProduto.getText().trim().replace(",", ".")));
            } catch (NumberFormatException e) {
                prod.setPrecoVenda(0.0);
            }

            int idFornecedorSelecionado = 0;
            if (cbFornecedorAtivo.getSelectedIndex() > 0) {
                String itemSelecionado = cbFornecedorAtivo.getSelectedItem().toString();

                idFornecedorSelecionado = Integer.parseInt(itemSelecionado.split(" - ")[0]);
            }

            prod.setFkFornecedor(idFornecedorSelecionado);

            model.ProdutoDAO dao = new model.ProdutoDAO();
            dao.Adicionar(prod);

            JOptionPane.showMessageDialog(this, "Produto cadastrado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            limparCampos();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro crítico ao salvar produto:\n" + e.getMessage(), "Erro de Banco", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCadastrarProdutoActionPerformed

    private void btnVoltarTPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarTPrincipalActionPerformed

        TelaInicial telaInicial = new TelaInicial(this.usuarioLogado);
        telaInicial.setLocationRelativeTo(null);
        telaInicial.setVisible(true);
        this.dispose();


    }//GEN-LAST:event_btnVoltarTPrincipalActionPerformed

    private void btnlimparCProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimparCProdutoActionPerformed

        limparCampos();
        txtProduto.requestFocusInWindow();

    }//GEN-LAST:event_btnlimparCProdutoActionPerformed

    private void btnListagemProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListagemProdutoActionPerformed

        ListagemProdutos telaListagem = new ListagemProdutos(this.usuarioLogado);
        telaListagem.setLocationRelativeTo(null);
        telaListagem.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnListagemProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastroProduto(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarProduto;
    private javax.swing.JButton btnListagemProduto;
    private javax.swing.JButton btnVoltarTPrincipal;
    private javax.swing.JButton btnlimparCProduto;
    private javax.swing.JComboBox<String> cbCategoria;
    private javax.swing.JComboBox<String> cbFornecedorAtivo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblDtValidade;
    private javax.swing.JLabel lblFornecedor;
    private javax.swing.JLabel lblObsFuncionario;
    private javax.swing.JLabel lblPrecoProduto;
    private javax.swing.JLabel lblProduto;
    private javax.swing.JLabel lblQdeProduto;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JRadioButton rbProdAtivo;
    private javax.swing.JTextPane txpObsFuncionario;
    private javax.swing.JTextField txtDtValidade;
    private javax.swing.JTextField txtPrecoProduto;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQdeProduto;
    // End of variables declaration//GEN-END:variables
}
