package view;

import model.KitServico;
import model.KitServicoDAO;
import model.Produto;
import model.ProdutoDAO;
import model.Servico;

public class CadastroKitServico extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroKitServico.class.getName());

    /**
     * Creates new form CadastroKitServico
     */
    public CadastroKitServico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblItensKit = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbServicos = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbProdutos = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();

        tblItensKit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblItensKit);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Kits de serviço oferecidos");

        jLabel2.setText("Selecione o Serviço:");

        cbServicos.addItemListener(this::cbServicosItemStateChanged);

        jLabel3.setText("Selecione o Produto para o Kit:");

        jLabel4.setText("Quantidade Utilizada:");

        btnAdicionar.setText("ADICIONAR");
        btnAdicionar.addActionListener(this::btnAdicionarActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(cbProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cbServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(btnAdicionar))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cbServicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cbProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdicionar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed

        try {
            // 1. VALIDAÇÃO: Verifica se o usuário selecionou algo e digitou a quantidade
            if (cbServicos.getSelectedItem() == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione um Serviço!");
                return;
            }
            if (cbProdutos.getSelectedItem() == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione um Produto!");
                return;
            }
            if (txtQuantidade.getText().trim().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Por favor, digite a Quantidade!");
                return;
            }

            // 2. CAPTURA: Faz o 'cast' (conversão) dos itens do ComboBox de volta para os seus Modelos
            Servico servicoSelecionado = (Servico) cbServicos.getSelectedItem();
            Produto produtoSelecionado = (Produto) cbProdutos.getSelectedItem();

            // Pega os IDs reais do banco de dados através dos objetos salvos
            int idServico = servicoSelecionado.getIdServico();
            int idProduto = produtoSelecionado.getIdProduto();

            // Lê a quantidade inserida na caixa de texto
            int quantidade = Integer.parseInt(txtQuantidade.getText().trim());

            if (quantidade <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "A quantidade deve ser maior do que zero!");
                return;
            }

            // 3. MODELO: Instancia o KitServico com as informações capturadas
            KitServico novoKitItem = new KitServico();
            novoKitItem.setServicoId(idServico);
            novoKitItem.setProdutoId(idProduto);
            novoKitItem.setQtidadeProdutoPorServico(quantidade);

            // 4. BANCO DE DADOS: Chama o seu DAO para gravar na tabela intermediária kitservico
            KitServicoDAO dao = new KitServicoDAO();
            dao.Adicionar(novoKitItem);

            // 5. SUCESSO: Avisa ao usuário e limpa o campo de quantidade
            javax.swing.JOptionPane.showMessageDialog(this, "Produto '" + produtoSelecionado.getNomeProduto() + "' adicionado ao kit com sucesso!");

            // Limpa a quantidade para a próxima inserção
            txtQuantidade.setText("");
            atualizarTabelaItensKit();
            // Opcional: Se tiver uma tabela visual embaixo, chame o método de atualizar a tabela aqui!
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro: A quantidade inserida é inválida! Use apenas números inteiros.");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao adicionar produto ao kit: " + e.getMessage());
        }

    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void cbServicosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbServicosItemStateChanged

        // Garante que o evento só rode quando uma nova opção for selecionada de fato
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            atualizarTabelaItensKit();
        }

    }//GEN-LAST:event_cbServicosItemStateChanged
    private void atualizarTabelaItensKit() {
        // 1. Verifica se existe algum serviço selecionado no ComboBox
        if (cbServicos.getSelectedItem() == null) {
            return;
        }

        // 2. Captura o objeto do serviço selecionado e descobre o ID dele
        Servico servicoSelecionado = (Servico) cbServicos.getSelectedItem();
        int idServico = servicoSelecionado.getIdServico();

        // 3. Instancia os DAOs necessários
        KitServicoDAO kitDAO = new KitServicoDAO();
        ProdutoDAO produtoDAO = new ProdutoDAO();

        // 4. Busca no banco de dados a lista de itens vinculados a esse serviço
        java.util.List<KitServico> listaItens = kitDAO.listarPorServico(idServico);

        // 5. Pega o modelo da tabela da tela e limpa as linhas antigas
        javax.swing.table.DefaultTableModel modeloDefault = (javax.swing.table.DefaultTableModel) tblItensKit.getModel();
        modeloDefault.setRowCount(0);

        // 6. Percorre os itens encontrados no banco
        for (KitServico item : listaItens) {
            // Como o KitServico só guarda o ID do produto, precisamos descobrir o nome dele
            // Vamos buscar a lista completa de produtos para achar o correspondente
            String nomeProduto = "Produto não encontrado";
            for (Produto prod : produtoDAO.listarTodos()) {
                if (prod.getIdProduto() == item.getProdutoId()) {
                    nomeProduto = prod.getNomeProduto();
                    break;
                }
            }

            // Monta a linha com o Nome do Produto e a Quantidade cadastrada no kit
            Object[] linha = {
                nomeProduto,
                item.getQtidadeProdutoPorServico()
            };
            modeloDefault.addRow(linha);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastroKitServico().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JComboBox<String> cbProdutos;
    private javax.swing.JComboBox<String> cbServicos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblItensKit;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
