package view;

import model.KitServico;
import model.KitServicoDAO;

public class CadastroKitServico extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroKitServico.class.getName());
    private javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> sorter;
    private model.Usuario usuarioLogado;

    public CadastroKitServico(model.Usuario usuario) {
        this.usuarioLogado = usuario;
        initComponents();

        cbServicos.removeAllItems();
        cbProdutos.removeAllItems();

        carregarServicosDoBanco();
        carregarProdutosDoBanco();

        atualizarTabelaItensKit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbServicos = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbProdutos = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItensKit = new javax.swing.JTable();
        btnTelaInicial = new javax.swing.JButton();
        btnLimparCampos = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtPesquisar = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Kits de serviço oferecidos");

        jLabel2.setText("Selecione o Serviço:");

        cbServicos.addItemListener(this::cbServicosItemStateChanged);
        cbServicos.addActionListener(this::cbServicosActionPerformed);

        jLabel3.setText("Selecione o Produto para o Kit:");

        jLabel4.setText("Quantidade Utilizada:");

        btnAdicionar.setText("ADICIONAR");
        btnAdicionar.addActionListener(this::btnAdicionarActionPerformed);

        tblItensKit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblItensKit);

        btnTelaInicial.setText("TELA INICIAL");
        btnTelaInicial.addActionListener(this::btnTelaInicialActionPerformed);

        btnLimparCampos.setText("Limpar");
        btnLimparCampos.addActionListener(this::btnLimparCamposActionPerformed);

        jLabel6.setText("Pesquisar:");

        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(this::btnPesquisarActionPerformed);

        btnExcluir.setText("Desabilitar o kit");
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTelaInicial))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPesquisar)
                        .addGap(90, 90, 90))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(cbProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cbServicos, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(btnAdicionar))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnLimparCampos)))))
                        .addGap(35, 35, 35)
                        .addComponent(btnExcluir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnTelaInicial))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cbServicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cbProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdicionar)
                            .addComponent(btnExcluir)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnLimparCampos)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesquisar)
                    .addComponent(jLabel6)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed

        try {

            if (cbServicos.getSelectedItem() == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione um Serviço!");
                return;
            }
            if (cbProdutos.getSelectedItem() == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione um Produto!");
                return;
            }
            if (txtQuantidade.getText().trim().isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Por favor, digite a Quantidade!");
                return;
            }

            int idServico = obterIdServicoSelecionado();

            String textoProduto = cbProdutos.getSelectedItem().toString();
            int idProduto = -1;
            String nomeProduto = textoProduto;

            if (textoProduto.contains("-")) {
                idProduto = Integer.parseInt(textoProduto.split("-")[0].trim());
                nomeProduto = textoProduto.split("-")[1].trim();
            } else {
                idProduto = Integer.parseInt(textoProduto.trim());
            }

            int quantidade = Integer.parseInt(txtQuantidade.getText().trim());

            if (idServico == -1 || idProduto == -1 || quantidade <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione opções válidas e uma quantidade maior que zero!");
                return;
            }

            KitServico novoKitItem = new KitServico();
            novoKitItem.setServicoId(idServico);
            novoKitItem.setProdutoId(idProduto);
            novoKitItem.setQtidadeProdutoPorServico(quantidade);

            KitServicoDAO dao = new KitServicoDAO();
            dao.Adicionar(novoKitItem);

            javax.swing.JOptionPane.showMessageDialog(this, "Produto '" + nomeProduto + "' adicionado ao kit com sucesso!");

            txtQuantidade.setText("");

            if (txtPesquisar != null) {
                txtPesquisar.setText("");
            }
            if (sorter != null) {
                sorter.setRowFilter(null);
            }

            atualizarTabelaItensKit();

        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro: A quantidade inserida é inválida! Use apenas números inteiros.");
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao adicionar produto ao kit: " + e.getMessage());
        }

    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void cbServicosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbServicosItemStateChanged

        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            atualizarTabelaItensKit();
        }
    }//GEN-LAST:event_cbServicosItemStateChanged

    private void btnTelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaInicialActionPerformed

        this.dispose();

    }//GEN-LAST:event_btnTelaInicialActionPerformed

    private void btnLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCamposActionPerformed

        if (cbServicos != null && cbServicos.getItemCount() > 0) {
            cbServicos.setSelectedIndex(0);
        }
        if (cbProdutos != null && cbProdutos.getItemCount() > 0) {
            cbProdutos.setSelectedIndex(0);
        }

        if (txtQuantidade != null) {
            txtQuantidade.setText("");
        }

        if (txtPesquisar != null) {
            txtPesquisar.setText("");
        }
        if (sorter != null) {
            sorter.setRowFilter(null);
        }

        if (cbServicos != null) {
            cbServicos.requestFocus();
        }
    }//GEN-LAST:event_btnLimparCamposActionPerformed

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased

        String texto = txtPesquisar.getText().trim();

        if (sorter == null) {
            return;
        }

        if (texto.isEmpty()) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + texto, 1));
        }
    }//GEN-LAST:event_txtPesquisarKeyReleased

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed

        txtPesquisarKeyReleased(null);

    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        int linhaSelecionada = tblItensKit.getSelectedRow();

        if (linhaSelecionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione um produto na tabela para remover do kit.");
            return;
        }

        int linhaModelo = tblItensKit.convertRowIndexToModel(linhaSelecionada);

        int idServico = (int) tblItensKit.getModel().getValueAt(linhaModelo, 0); // Coluna 0 é o ID do Serviço
        String nomeServico = tblItensKit.getModel().getValueAt(linhaModelo, 1).toString();

        String valorColunaProduto = tblItensKit.getModel().getValueAt(linhaModelo, 2).toString();
        int idProduto = Integer.parseInt(valorColunaProduto);

        String nomeProduto = tblItensKit.getModel().getValueAt(linhaModelo, 3).toString();

        int confirmar = javax.swing.JOptionPane.showConfirmDialog(this,
                "Tem certeza que deseja desativar o produto '" + nomeProduto + "' do kit '" + nomeServico + "'?",
                "Confirmar Remoção", javax.swing.JOptionPane.YES_NO_OPTION);

        if (confirmar == javax.swing.JOptionPane.YES_OPTION) {
            try {

                KitServicoDAO dao = new KitServicoDAO();
                dao.excluirItemDoKit(idServico, idProduto);

                javax.swing.JOptionPane.showMessageDialog(this, "Produto desativado do kit com sucesso!");

                if (txtPesquisar != null) {
                    txtPesquisar.setText("");
                }
                if (sorter != null) {
                    sorter.setRowFilter(null);
                }

                atualizarTabelaItensKit();

            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Erro ao remover item do kit: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void cbServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbServicosActionPerformed

        atualizarTabelaItensKit();

    }//GEN-LAST:event_cbServicosActionPerformed

    private void atualizarTabelaItensKit() {

        String[] colunas = {"ID Serviço", "Nome do Kit / Serviço", "ID Prod", "Produto Utilizado", "Qtd Gasta"};

        javax.swing.table.DefaultTableModel modeloDefault = new javax.swing.table.DefaultTableModel(colunas, 0);

        tblItensKit.setAutoCreateColumnsFromModel(true);
        tblItensKit.setModel(modeloDefault);

        try {

            KitServicoDAO dao = new KitServicoDAO();
            java.util.List<KitServico> lista = dao.listarPorServico(0);

            for (KitServico ks : lista) {
                Object[] row = {
                    ks.getServicoId(),
                    ks.getNomeServico(),
                    ks.getProdutoId(),
                    ks.getNomeProduto(),
                    ks.getQtidadeProdutoPorServico()
                };
                modeloDefault.addRow(row);
            }

            sorter = new javax.swing.table.TableRowSorter<>(modeloDefault);
            tblItensKit.setRowSorter(sorter);

            if (tblItensKit.getColumnModel().getColumnCount() >= 5) {

                tblItensKit.getColumnModel().getColumn(0).setMinWidth(0);
                tblItensKit.getColumnModel().getColumn(0).setMaxWidth(0);
                tblItensKit.getColumnModel().getColumn(0).setPreferredWidth(0);

                tblItensKit.getColumnModel().getColumn(2).setMinWidth(0);
                tblItensKit.getColumnModel().getColumn(2).setMaxWidth(0);
                tblItensKit.getColumnModel().getColumn(2).setPreferredWidth(0);
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao carregar tabela de itens: " + e.getMessage());
        }
    }

    private int obterIdServicoSelecionado() {
        if (cbServicos == null || cbServicos.getSelectedItem() == null) {
            return -1;
        }

        String item = cbServicos.getSelectedItem().toString();

        if (item.startsWith("Selecione")) {
            return -1;
        }

        if (cbServicos.getSelectedItem() instanceof model.Servico) {
            model.Servico s = (model.Servico) cbServicos.getSelectedItem();
            return s.getIdServico();
        }

        try {
            if (item.contains("-")) {
                return Integer.parseInt(item.split("-")[0].trim());
            }
            return Integer.parseInt(item.trim());
        } catch (Exception e) {
            return -1;
        }
    }

    private void mostrarTodosOsKitsNaTabela() {

        javax.swing.table.DefaultTableModel modeloDefault = (javax.swing.table.DefaultTableModel) tblItensKit.getModel();

        String[] colunas = {"ID Prod", "Produto Utilizado", "Qtd Gasta"};
        modeloDefault.setColumnIdentifiers(colunas);
        modeloDefault.setRowCount(0);

        try {
            KitServicoDAO dao = new KitServicoDAO();

            java.util.List<KitServico> lista = dao.listarTodosOsKits();

            for (KitServico ks : lista) {
                Object[] linha = {
                    ks.getProdutoId(),
                    ks.getNomeProduto(),
                    ks.getQtidadeProdutoPorServico()
                };
                modeloDefault.addRow(linha);
            }

            sorter = new javax.swing.table.TableRowSorter<>(modeloDefault);
            tblItensKit.setRowSorter(sorter);

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao carregar listagem completa: " + e.getMessage());
        }
    }

    private void carregarServicosDoBanco() {
        try {
            cbServicos.removeAllItems();

            cbServicos.addItem("Selecione um serviço...");

            model.ServicoDAO sDao = new model.ServicoDAO();
            java.util.List<model.Servico> lista = sDao.listarTodos();

            for (model.Servico s : lista) {

                cbServicos.addItem(s.getIdServico() + " - " + s.getServico());
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao carregar serviços no menu: " + e.getMessage());
        }
    }

    private void carregarProdutosDoBanco() {
        try {
            cbProdutos.removeAllItems();

            cbProdutos.addItem("Selecione um produto...");

            model.ProdutoDAO pDao = new model.ProdutoDAO();
            java.util.List<model.Produto> lista = pDao.listarTodos();

            for (model.Produto p : lista) {

                cbProdutos.addItem(p.getIdProduto() + " - " + p.getNomeProduto());
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao carregar produtos no menu: " + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastroKitServico(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimparCampos;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnTelaInicial;
    private javax.swing.JComboBox<String> cbProdutos;
    private javax.swing.JComboBox<String> cbServicos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblItensKit;
    private javax.swing.JTextField txtPesquisar;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
