package view;

import javax.swing.JOptionPane;

public class CadastroFuncionario extends javax.swing.JFrame {

    private javax.swing.DefaultListModel<String> listaModelTelefones = new javax.swing.DefaultListModel<>();
    private java.util.List<model.Telefone> telefonesParaSalvar = new java.util.ArrayList<>();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName());
    private int idEnderecoSelecionado = 0;
    private model.Usuario usuarioLogado;

    /**
     * Creates new form CadastroFuncionario
     */
    public CadastroFuncionario(model.Usuario usuario) {
        initComponents();
        this.usuarioLogado = usuario;
        listTelefones.setModel(listaModelTelefones);

        limparCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnlimparFuncionario = new javax.swing.JButton();
        btnCadastrarFuncionario = new javax.swing.JButton();
        btnVoltarTPrincipal = new javax.swing.JButton();
        rbFuncAtivo = new javax.swing.JRadioButton();
        lblFuncionario = new javax.swing.JLabel();
        txtFuncionario = new javax.swing.JTextField();
        lblCpf = new javax.swing.JLabel();
        txtCpfFuncionario = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmailFuncionario = new javax.swing.JTextField();
        lblDtNascimento = new javax.swing.JLabel();
        txtDtNascFuncionario = new javax.swing.JTextField();
        lblDtContrato = new javax.swing.JLabel();
        txtDtContrato = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        txtTelFuncionario = new javax.swing.JTextField();
        lblFuncao = new javax.swing.JLabel();
        lblValorServico = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblCartTrabalho = new javax.swing.JLabel();
        cbFuncao = new javax.swing.JComboBox<>();
        txtValorServico = new javax.swing.JTextField();
        txtCartTrabalho = new javax.swing.JTextField();
        cbHorario = new javax.swing.JComboBox<>();
        lblDtCadastro = new javax.swing.JLabel();
        txtDtCadastro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnAdicionarTel = new javax.swing.JButton();
        btnAdicionarEndereco = new javax.swing.JButton();
        btnListagemFuncionarios = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        cbTipoTel = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtDdd = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        listTelefones = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro Funcionário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        lblTitulo.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        lblTitulo.setText("Instituto da Beleza");

        btnlimparFuncionario.setBackground(new java.awt.Color(255, 255, 0));
        btnlimparFuncionario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnlimparFuncionario.setText("Limpar");
        btnlimparFuncionario.setToolTipText("Limpa o formulário");
        btnlimparFuncionario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnlimparFuncionario.addActionListener(this::btnlimparFuncionarioActionPerformed);

        btnCadastrarFuncionario.setBackground(new java.awt.Color(255, 255, 0));
        btnCadastrarFuncionario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCadastrarFuncionario.setText("Cadastrar");
        btnCadastrarFuncionario.setToolTipText("Cadastro de Cliente");
        btnCadastrarFuncionario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCadastrarFuncionario.addActionListener(this::btnCadastrarFuncionarioActionPerformed);

        btnVoltarTPrincipal.setBackground(new java.awt.Color(255, 255, 0));
        btnVoltarTPrincipal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVoltarTPrincipal.setText("Voltar");
        btnVoltarTPrincipal.setToolTipText("Volta para a tela principal");
        btnVoltarTPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVoltarTPrincipal.addActionListener(this::btnVoltarTPrincipalActionPerformed);

        rbFuncAtivo.setText("Funcionário ativo");
        rbFuncAtivo.setToolTipText("Marque quando o cliente for assíduo");

        lblFuncionario.setLabelFor(txtFuncionario);
        lblFuncionario.setText("Funcionário(a):");

        txtFuncionario.setToolTipText("Escreva o nome completo");

        lblCpf.setLabelFor(txtCpfFuncionario);
        lblCpf.setText("CPF:");

        txtCpfFuncionario.setToolTipText("Escreva o CPF");

        lblEmail.setLabelFor(txtEmailFuncionario);
        lblEmail.setText("E-mail");

        txtEmailFuncionario.setToolTipText("Email não obrigatório");

        lblDtNascimento.setLabelFor(txtDtNascFuncionario);
        lblDtNascimento.setText("Data de Nascimento:");

        txtDtNascFuncionario.setToolTipText("Data válida com ano XXXX");

        lblDtContrato.setLabelFor(txtDtContrato);
        lblDtContrato.setText("Data de Contrato:");

        txtDtContrato.setToolTipText("Data de hoje, ano XXXX");

        lblTelefone.setLabelFor(txtTelFuncionario);
        lblTelefone.setText("Telefone:");

        txtTelFuncionario.setToolTipText("Telefone ou celular com DDD");

        lblFuncao.setLabelFor(cbFuncao);
        lblFuncao.setText("Função:");

        lblValorServico.setText("Valor do Serviço:");

        jLabel3.setLabelFor(cbHorario);
        jLabel3.setText("Disponibilidade de horário:");

        lblCartTrabalho.setLabelFor(txtCartTrabalho);
        lblCartTrabalho.setText("Carteira de trabalho No:");

        cbFuncao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a função:", "Gerência", "Recepção", "Atendente" }));

        cbHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o horário de trabalho", "Matutino de Terça a Sábado", "Vespertino de Terça a Sábado", "Integral de Terça a Sábado", "Integral Quinta a Sábado" }));
        cbHorario.setToolTipText("Selecione um modelo de horário de trabalho");

        lblDtCadastro.setText("Data de Cadastro:");

        jLabel1.setText("DDD:");

        btnAdicionarTel.setText("Cadastrar telefone");
        btnAdicionarTel.addActionListener(this::btnAdicionarTelActionPerformed);

        btnAdicionarEndereco.setText("Adicionar Endereço");
        btnAdicionarEndereco.addActionListener(this::btnAdicionarEnderecoActionPerformed);

        btnListagemFuncionarios.setBackground(new java.awt.Color(255, 255, 0));
        btnListagemFuncionarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnListagemFuncionarios.setText("Listagem");
        btnListagemFuncionarios.setToolTipText("Volta para a tela principal");
        btnListagemFuncionarios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnListagemFuncionarios.addActionListener(this::btnListagemFuncionariosActionPerformed);

        cbTipoTel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o tipo", "celular", "trabalho", "casa" }));
        jScrollPane4.setViewportView(cbTipoTel);

        jScrollPane5.setViewportView(txtDdd);

        jScrollPane6.setViewportView(listTelefones);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCpfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblFuncionario)
                        .addGap(18, 18, 18)
                        .addComponent(txtFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbFuncAtivo)
                .addGap(354, 354, 354))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblFuncao)
                                .addGap(18, 18, 18)
                                .addComponent(cbFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblDtContrato)
                                .addGap(18, 18, 18)
                                .addComponent(txtDtContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(cbHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblValorServico)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtValorServico, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblCartTrabalho)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtCartTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCadastrarFuncionario)
                                .addGap(71, 71, 71)
                                .addComponent(btnlimparFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnVoltarTPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(17, 17, 17)
                                                .addComponent(btnListagemFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(btnAdicionarEndereco))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnAdicionarTel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblTelefone)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTelFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(46, 46, 46)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(31, 31, 31))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(415, 415, 415)
                        .addComponent(lblTitulo))
                    .addComponent(lblCpf)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lblEmail)
                            .addGap(18, 18, 18)
                            .addComponent(txtEmailFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lblDtNascimento)
                            .addGap(18, 18, 18)
                            .addComponent(txtDtNascFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(127, 127, 127)
                            .addComponent(lblDtCadastro)
                            .addGap(18, 18, 18)
                            .addComponent(txtDtCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbFuncAtivo)
                    .addComponent(lblFuncionario)
                    .addComponent(txtFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCpf)
                    .addComponent(txtCpfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDtNascimento)
                    .addComponent(txtDtNascFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDtCadastro)
                    .addComponent(txtDtCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail)
                            .addComponent(txtEmailFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbFuncao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFuncao, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDtContrato)
                            .addComponent(txtDtContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cbHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCartTrabalho)
                                    .addComponent(txtCartTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAdicionarTel))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblValorServico)
                                    .addComponent(txtValorServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1)
                                .addComponent(btnAdicionarEndereco)
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnCadastrarFuncionario)
                                    .addComponent(btnlimparFuncionario)
                                    .addComponent(btnVoltarTPrincipal)
                                    .addComponent(btnListagemFuncionarios)))
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(136, 136, 136))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTelefone))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarFuncionarioActionPerformed

        if (txtFuncionario.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "O nome do funcionário é obrigatório!", "Erro de Validação", JOptionPane.WARNING_MESSAGE);
            txtFuncionario.requestFocus();
            return;
        }
        if (txtCartTrabalho.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "A carteira de trabalho é obrigatória!", "Erro de Validação", JOptionPane.WARNING_MESSAGE);
            txtCartTrabalho.requestFocus();
            return;
        }

        model.Funcionario func = new model.Funcionario();

        func.setNomeFuncionario(txtFuncionario.getText().trim());
        func.setCpf(txtCpfFuncionario.getText().trim());
        func.setEmail(txtEmailFuncionario.getText().trim());
        func.setCarteiraTrabalho(txtCartTrabalho.getText().trim());

        java.text.SimpleDateFormat formatoData = new java.text.SimpleDateFormat("dd/MM/yyyy");
        formatoData.setLenient(false);

        try {
            String dtNascTexto = txtDtNascFuncionario.getText().trim().replace("/", "").trim();

            if (!dtNascTexto.isEmpty()) {
                java.util.Date dataUtil = formatoData.parse(txtDtNascFuncionario.getText().trim());
                func.setDataNascimento(dataUtil);
            } else {
                func.setDataNascimento(null);
            }
        } catch (java.text.ParseException ex) {
            JOptionPane.showMessageDialog(this, "Data de Nascimento inválida! Use o formato dd/MM/yyyy.", "Erro de Validação", JOptionPane.WARNING_MESSAGE);
            txtDtNascFuncionario.requestFocus();
            return;
        }

        try {
            String dtContratoTexto = txtDtContrato.getText().trim().replace("/", "").trim();
            if (!dtContratoTexto.isEmpty()) {
                java.util.Date dataUtil = formatoData.parse(txtDtContrato.getText().trim());
                func.setDataCadastro(dataUtil);

            } else {
                func.setDataCadastro(null);
                func.setDataContratacao(null);
            }
        } catch (java.text.ParseException ex) {
            JOptionPane.showMessageDialog(this, "Data de Contrato/Cadastro inválida! Use o formato dd/MM/yyyy.", "Erro de Validação", JOptionPane.WARNING_MESSAGE);
            txtDtContrato.requestFocus();
            return;
        }

        if (cbFuncao.getSelectedIndex() > 0) {
            func.setFuncao(cbFuncao.getSelectedItem().toString());
        } else {
            func.setFuncao("");
        }

        if (cbHorario.getSelectedIndex() > 0) {
            func.setDisponibilidadeDeHorario(cbHorario.getSelectedItem().toString());
        } else {
            func.setDisponibilidadeDeHorario("");
        }

        try {
            String valorTexto = txtValorServico.getText().trim().replace(",", ".");
            double valor = valorTexto.isEmpty() ? 0.0 : Double.parseDouble(valorTexto);
            func.setValorDoServico(valor);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Valor do serviço inválido! Use apenas números.", "Erro", JOptionPane.ERROR_MESSAGE);
            txtValorServico.requestFocus();
            return;
        }

        func.setAtivo(rbFuncAtivo.isSelected());

        try {
            model.FuncionarioDAO dao = new model.FuncionarioDAO();

            java.util.List<String> listaTelefones = new java.util.ArrayList<>();
            if (!txtTelFuncionario.getText().trim().isEmpty()) {
                listaTelefones.add(txtTelFuncionario.getText().trim());
            }

            func.setFkEndereco(0);

            dao.Adicionar(func, telefonesParaSalvar);

            JOptionPane.showMessageDialog(this, "Funcionário cadastrado com sucesso no banco de dados!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

            btnlimparFuncionarioActionPerformed(null);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro crítico ao salvar no banco:\n" + e.getMessage(), "Erro de Banco", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnCadastrarFuncionarioActionPerformed

    private void btnVoltarTPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarTPrincipalActionPerformed

        TelaInicial telaInicial = new TelaInicial(this.usuarioLogado);
        telaInicial.setLocationRelativeTo(null);
        telaInicial.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnVoltarTPrincipalActionPerformed

    private void btnlimparFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimparFuncionarioActionPerformed

        limparCampos();
        listaModelTelefones.clear();
        telefonesParaSalvar.clear();

    }//GEN-LAST:event_btnlimparFuncionarioActionPerformed

    private void btnAdicionarTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarTelActionPerformed

        String ddd = txtDdd.getText().trim();
        String numero = txtTelFuncionario.getText().trim();
        String tipo = cbTipoTel.getSelectedItem().toString();

        if (ddd.isEmpty() || numero.isEmpty() || cbTipoTel.getSelectedIndex() == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Preencha o DDD, Telefone e selecione o Tipo!");
            return;
        }

        model.Telefone novoTel = new model.Telefone();
        novoTel.setDdd(ddd);
        novoTel.setTelefone(numero);
        novoTel.setTelefoneTipo(tipo);

        telefonesParaSalvar.add(novoTel);

        listaModelTelefones.addElement(tipo + ": (" + ddd + ") " + numero);

        txtDdd.setText("");
        txtTelFuncionario.setText("");
        cbTipoTel.setSelectedIndex(0);
    }//GEN-LAST:event_btnAdicionarTelActionPerformed

    private void btnAdicionarEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarEnderecoActionPerformed

        TelaEndereco telaEnd = new TelaEndereco(this, true);
        telaEnd.setLocationRelativeTo(this);
        telaEnd.setVisible(true);
        this.idEnderecoSelecionado = telaEnd.getIdEnderecoGerado();

        if (this.idEnderecoSelecionado > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Endereço vinculado! ID: " + this.idEnderecoSelecionado);
        }
    }//GEN-LAST:event_btnAdicionarEnderecoActionPerformed

    private void btnListagemFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListagemFuncionariosActionPerformed

        ListagemFuncionarios telaListagem = new ListagemFuncionarios(this.usuarioLogado);
        telaListagem.setLocationRelativeTo(null);
        telaListagem.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnListagemFuncionariosActionPerformed

    private void limparCampos() {
        txtFuncionario.setText("");
        txtCpfFuncionario.setText("");
        txtDtNascFuncionario.setText("");
        txtEmailFuncionario.setText("");
        txtTelFuncionario.setText("");
        cbFuncao.setSelectedIndex(0);
        txtCartTrabalho.setText("");
        txtDtContrato.setText("");
        txtValorServico.setText("");
        cbHorario.setSelectedIndex(0);
        txtDtCadastro.setText("");

        rbFuncAtivo.setSelected(true);
        txtFuncionario.requestFocusInWindow();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastroFuncionario(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarEndereco;
    private javax.swing.JButton btnAdicionarTel;
    private javax.swing.JButton btnCadastrarFuncionario;
    private javax.swing.JButton btnListagemFuncionarios;
    private javax.swing.JButton btnVoltarTPrincipal;
    private javax.swing.JButton btnlimparFuncionario;
    private javax.swing.JComboBox<String> cbFuncao;
    private javax.swing.JComboBox<String> cbHorario;
    private javax.swing.JComboBox<String> cbTipoTel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblCartTrabalho;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblDtCadastro;
    private javax.swing.JLabel lblDtContrato;
    private javax.swing.JLabel lblDtNascimento;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFuncao;
    private javax.swing.JLabel lblFuncionario;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblValorServico;
    private javax.swing.JList<String> listTelefones;
    private javax.swing.JRadioButton rbFuncAtivo;
    private javax.swing.JTextField txtCartTrabalho;
    private javax.swing.JTextField txtCpfFuncionario;
    private javax.swing.JTextField txtDdd;
    private javax.swing.JTextField txtDtCadastro;
    private javax.swing.JTextField txtDtContrato;
    private javax.swing.JTextField txtDtNascFuncionario;
    private javax.swing.JTextField txtEmailFuncionario;
    private javax.swing.JTextField txtFuncionario;
    private javax.swing.JTextField txtTelFuncionario;
    private javax.swing.JTextField txtValorServico;
    // End of variables declaration//GEN-END:variables
}
