package view;

import javax.swing.JOptionPane;

public class CadastroFornecedor extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroFornecedor.class.getName());

    private int idEnderecoSelecionado = 0;
    private javax.swing.DefaultListModel<String> listaModelTelefones = new javax.swing.DefaultListModel<>();
    private java.util.List<model.Telefone> telefonesParaSalvar = new java.util.ArrayList<>();
    private model.Usuario usuarioLogado;

    /**
     * Creates new form CadastroFornecedor
     */
    public CadastroFornecedor(model.Usuario usuario) {
        initComponents();
        this.usuarioLogado = usuario;
        listTelefones.setModel(listaModelTelefones);
        limparCampos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnlimparCFornecedor = new javax.swing.JButton();
        btnCadastrarFornecedor = new javax.swing.JButton();
        btnVoltarTPrincipalFornecedor = new javax.swing.JButton();
        rbFornecedorAtivo = new javax.swing.JRadioButton();
        lblFornecedor = new javax.swing.JLabel();
        txtFornecedor = new javax.swing.JTextField();
        lblCnpj = new javax.swing.JLabel();
        txtCnpj = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmailFornecedor = new javax.swing.JTextField();
        lblNomeContato = new javax.swing.JLabel();
        txtNomeContato = new javax.swing.JTextField();
        lblDtCadFornecedor = new javax.swing.JLabel();
        txtDtCadFornecedor = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        txtTelFornecedor = new javax.swing.JTextField();
        lblObservacoes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txpObsFornecedor = new javax.swing.JTextPane();
        btnListagemFornecedores = new javax.swing.JButton();
        btnAdicionarEndereco = new javax.swing.JButton();
        btnAdicionarTel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDdd = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        listTelefones = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        cbTipoTel = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro Fornecedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        lblTitulo.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        lblTitulo.setText("Instituto da Beleza");

        btnlimparCFornecedor.setBackground(new java.awt.Color(255, 255, 0));
        btnlimparCFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnlimparCFornecedor.setText("Limpar");
        btnlimparCFornecedor.setToolTipText("Limpa o formulário");
        btnlimparCFornecedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnlimparCFornecedor.addActionListener(this::btnlimparCFornecedorActionPerformed);

        btnCadastrarFornecedor.setBackground(new java.awt.Color(255, 255, 0));
        btnCadastrarFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCadastrarFornecedor.setText("Cadastrar");
        btnCadastrarFornecedor.setToolTipText("Cadastro de Fornecedor");
        btnCadastrarFornecedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCadastrarFornecedor.addActionListener(this::btnCadastrarFornecedorActionPerformed);

        btnVoltarTPrincipalFornecedor.setBackground(new java.awt.Color(255, 255, 0));
        btnVoltarTPrincipalFornecedor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVoltarTPrincipalFornecedor.setText("Voltar");
        btnVoltarTPrincipalFornecedor.setToolTipText("Volta para a tela principal");
        btnVoltarTPrincipalFornecedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVoltarTPrincipalFornecedor.addActionListener(this::btnVoltarTPrincipalFornecedorActionPerformed);

        rbFornecedorAtivo.setText("Fornecedor Ativo");
        rbFornecedorAtivo.setToolTipText("Marque quando o cliente for assíduo");

        lblFornecedor.setText("Empresa:");

        txtFornecedor.setToolTipText("Escreva o nome completo");

        lblCnpj.setText("CNPJ:");

        txtCnpj.setToolTipText("Escreva o CPF");

        lblEmail.setText("E-mail");

        txtEmailFornecedor.setToolTipText("Email não obrigatório");

        lblNomeContato.setText("Contato:");

        txtNomeContato.setToolTipText("Data válida com ano XXXX");

        lblDtCadFornecedor.setText("Data de Cadastro:");

        txtDtCadFornecedor.setToolTipText("Data de hoje, ano XXXX");

        lblTelefone.setText("Telefone:");

        txtTelFornecedor.setToolTipText("Telefone ou celular com DDD");

        lblObservacoes.setText("Observações:");

        txpObsFornecedor.setForeground(new java.awt.Color(153, 153, 153));
        txpObsFornecedor.setToolTipText("Observações sobre produtos e entregas");
        jScrollPane1.setViewportView(txpObsFornecedor);

        btnListagemFornecedores.setBackground(new java.awt.Color(255, 255, 0));
        btnListagemFornecedores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnListagemFornecedores.setText("Listagem");
        btnListagemFornecedores.setToolTipText("Volta para a tela principal");
        btnListagemFornecedores.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnListagemFornecedores.addActionListener(this::btnListagemFornecedoresActionPerformed);

        btnAdicionarEndereco.setText("Adicionar Endereço");
        btnAdicionarEndereco.addActionListener(this::btnAdicionarEnderecoActionPerformed);

        btnAdicionarTel.setText("Cadastrar o telefone");
        btnAdicionarTel.addActionListener(this::btnAdicionarTelActionPerformed);

        jLabel1.setText("DDD:");

        jScrollPane2.setViewportView(txtDdd);

        jScrollPane3.setViewportView(listTelefones);

        cbTipoTel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o tipo", "celular", "trabalho", "casa" }));
        jScrollPane4.setViewportView(cbTipoTel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblFornecedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblCnpj)
                    .addComponent(lblObservacoes)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTelefone)
                                .addGap(18, 18, 18)
                                .addComponent(txtTelFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNomeContato)
                                    .addComponent(lblEmail))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNomeContato, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmailFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(61, 61, 61)
                        .addComponent(lblDtCadFornecedor)
                        .addGap(18, 18, 18)
                        .addComponent(txtDtCadFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAdicionarTel, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(rbFornecedorAtivo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addContainerGap(105, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCadastrarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(btnlimparCFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(btnVoltarTPrincipalFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99)
                .addComponent(btnListagemFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(btnAdicionarEndereco)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbFornecedorAtivo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFornecedor)
                            .addComponent(txtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCnpj)
                            .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomeContato)
                            .addComponent(txtNomeContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDtCadFornecedor)
                            .addComponent(txtDtCadFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmailFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblObservacoes)
                            .addComponent(btnAdicionarTel)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTelefone)
                                    .addComponent(txtTelFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(31, 31, 31))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCadastrarFornecedor)
                            .addComponent(btnlimparCFornecedor)
                            .addComponent(btnVoltarTPrincipalFornecedor)
                            .addComponent(btnListagemFornecedores))
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdicionarEndereco)
                        .addGap(145, 145, 145))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarFornecedorActionPerformed

        if (txtFornecedor.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo Empresa (Razão Social) é obrigatório!", "Erro de Validação", JOptionPane.WARNING_MESSAGE);
            txtFornecedor.requestFocus();
            return;
        }

        try {

            model.Fornecedor forn = new model.Fornecedor();
            forn.setRazaoSocial(txtFornecedor.getText().trim());
            forn.setCnpj(txtCnpj.getText().trim());
            forn.setEmailFornecedor(txtEmailFornecedor.getText().trim());
            forn.setPessoaDeContato(txtNomeContato.getText().trim());
            forn.setObservacao(txpObsFornecedor.getText().trim());
            forn.setAtivo(rbFornecedorAtivo.isSelected());

            forn.setFkEndereco(this.idEnderecoSelecionado);

            model.FornecedorDAO dao = new model.FornecedorDAO();
            dao.Adicionar(forn, telefonesParaSalvar);

            JOptionPane.showMessageDialog(this, "Fornecedor cadastrado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            limparCampos();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro crítico ao salvar fornecedor:\n" + e.getMessage(), "Erro de Banco", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnCadastrarFornecedorActionPerformed

    private void btnVoltarTPrincipalFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarTPrincipalFornecedorActionPerformed

        TelaInicial telaInicial = new TelaInicial(this.usuarioLogado);
        telaInicial.setLocationRelativeTo(null);
        telaInicial.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnVoltarTPrincipalFornecedorActionPerformed

    private void btnlimparCFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimparCFornecedorActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnlimparCFornecedorActionPerformed

    private void btnListagemFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListagemFornecedoresActionPerformed

        ListagemFornecedores telaListagem = new ListagemFornecedores(this.usuarioLogado);
        telaListagem.setLocationRelativeTo(null);
        telaListagem.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnListagemFornecedoresActionPerformed

    private void btnAdicionarEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarEnderecoActionPerformed

        TelaEndereco telaEnd = new TelaEndereco(this, true);
        telaEnd.setLocationRelativeTo(this);
        telaEnd.setVisible(true);
        this.idEnderecoSelecionado = telaEnd.getIdEnderecoGerado();
        if (this.idEnderecoSelecionado > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Endereço vinculado! ID: " + this.idEnderecoSelecionado);
        }
    }//GEN-LAST:event_btnAdicionarEnderecoActionPerformed

    private void btnAdicionarTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarTelActionPerformed
        String ddd = txtDdd.getText().trim();
        String numero = txtTelFornecedor.getText().trim();
        String tipo = cbTipoTel.getSelectedItem().toString();

        if (ddd.isEmpty() || numero.isEmpty() || cbTipoTel.getSelectedIndex() == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Preencha o DDD, Telefone e selecione o Tipo!");
            return;
        }

        model.Telefone novoTel = new model.Telefone();
        novoTel.setDdd(ddd);
        novoTel.setTelefone(numero);
        novoTel.setTelefoneTipo(tipo);

        telefonesParaSalvar.add(novoTel);

        listaModelTelefones.addElement(tipo + ": (" + ddd + ") " + numero);

        txtDdd.setText("");
        txtTelFornecedor.setText("");
        cbTipoTel.setSelectedIndex(0);

    }//GEN-LAST:event_btnAdicionarTelActionPerformed

    private void limparCampos() {
        txtFornecedor.setText("");
        txtCnpj.setText("");
        txtEmailFornecedor.setText("");
        txtNomeContato.setText("");
        txtTelFornecedor.setText("");
        txtDtCadFornecedor.setText("");
        txpObsFornecedor.setText("");
        rbFornecedorAtivo.setSelected(true);
        txtFornecedor.requestFocus();
        txtDdd.setText("");
        txtTelFornecedor.setText("");
        cbTipoTel.setSelectedIndex(0);

        if (this.telefonesParaSalvar != null) {
            this.telefonesParaSalvar.clear();

            if (listTelefones.getModel() instanceof javax.swing.DefaultListModel) {
                javax.swing.DefaultListModel<?> modelList = (javax.swing.DefaultListModel<?>) listTelefones.getModel();
                modelList.clear();

            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CadastroFornecedor(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarEndereco;
    private javax.swing.JButton btnAdicionarTel;
    private javax.swing.JButton btnCadastrarFornecedor;
    private javax.swing.JButton btnListagemFornecedores;
    private javax.swing.JButton btnVoltarTPrincipalFornecedor;
    private javax.swing.JButton btnlimparCFornecedor;
    private javax.swing.JComboBox<String> cbTipoTel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblCnpj;
    private javax.swing.JLabel lblDtCadFornecedor;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFornecedor;
    private javax.swing.JLabel lblNomeContato;
    private javax.swing.JLabel lblObservacoes;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JList<String> listTelefones;
    private javax.swing.JRadioButton rbFornecedorAtivo;
    private javax.swing.JTextPane txpObsFornecedor;
    private javax.swing.JTextField txtCnpj;
    private javax.swing.JTextField txtDdd;
    private javax.swing.JTextField txtDtCadFornecedor;
    private javax.swing.JTextField txtEmailFornecedor;
    private javax.swing.JTextField txtFornecedor;
    private javax.swing.JTextField txtNomeContato;
    private javax.swing.JTextField txtTelFornecedor;
    // End of variables declaration//GEN-END:variables
}
