package view;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Fornecedor;
import model.FornecedorDAO;
import model.Telefone;
import model.TelefoneDAO;
import model.Usuario;

/**
 *
 * @author karen
 */
public class ListagemFornecedores extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ListagemFornecedores.class.getName());
    // ADICIONE ESTAS TRÊS LINHAS LOGO NO INÍCIO DA CLASSE:
    private Usuario usuarioLogado;
    private TableRowSorter<DefaultTableModel> sorter; // Resolve o erro da linha 263 e 266

    /**
     * Creates new form ListagemFornecedores
     */
       // SUBSTITUA o seu construtor por este aqui:
    public ListagemFornecedores(Usuario usuario) {
        
        initComponents();
             this.usuarioLogado = usuario;
        // Força os títulos a aparecerem corretamente
        jScrollPane1.setViewportView(tblFornecedores);
        
        // Preenche a tabela visual
        preencherTabela();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFornecedorPesquisar = new javax.swing.JTextField();
        btnPesquisarNome = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFornecedores = new javax.swing.JTable();
        btnCadastroFornecedor = new javax.swing.JButton();
        btnExcluirFornecedor = new javax.swing.JButton();
        btnVoltarTelaInicial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Fornecedores");

        jLabel2.setText("Nome do Fornecedor:");

        txtFornecedorPesquisar.addActionListener(this::txtFornecedorPesquisarActionPerformed);

        btnPesquisarNome.setText("PESQUISAR");
        btnPesquisarNome.addActionListener(this::btnPesquisarNomeActionPerformed);

        tblFornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Empresa", "CNPJ", "Contato", "Telefone", "Ativo(VIP)"
            }
        ));
        jScrollPane1.setViewportView(tblFornecedores);

        btnCadastroFornecedor.setText("+ NOVO");
        btnCadastroFornecedor.addActionListener(this::btnCadastroFornecedorActionPerformed);

        btnExcluirFornecedor.setText("EXCLUIR");
        btnExcluirFornecedor.addActionListener(this::btnExcluirFornecedorActionPerformed);

        btnVoltarTelaInicial.setText("TELA INICIAL");
        btnVoltarTelaInicial.addActionListener(this::btnVoltarTelaInicialActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtFornecedorPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(btnPesquisarNome)))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnCadastroFornecedor)
                .addGap(133, 133, 133)
                .addComponent(btnExcluirFornecedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltarTelaInicial)
                .addGap(137, 137, 137))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFornecedorPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarNome))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastroFornecedor)
                    .addComponent(btnExcluirFornecedor)
                    .addComponent(btnVoltarTelaInicial))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFornecedorPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFornecedorPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFornecedorPesquisarActionPerformed

    private void btnPesquisarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarNomeActionPerformed
        filtrarTabela();
    }//GEN-LAST:event_btnPesquisarNomeActionPerformed

    private void btnCadastroFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroFornecedorActionPerformed

        CadastroFornecedor telaCadastro = new CadastroFornecedor(this.usuarioLogado);
        telaCadastro.setVisible(true);
        this.dispose(); // Fecha a tela de listagem atual
    }//GEN-LAST:event_btnCadastroFornecedorActionPerformed

    private void btnExcluirFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirFornecedorActionPerformed
    
            int linhaSelecionada = tblFornecedores.getSelectedRow();

    if (linhaSelecionada == -1) {
        JOptionPane.showMessageDialog(this, "Por favor, selecione um fornecedor na tabela para excluir.", "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
    }

// SUBSTITUA A LINHA DO ERRO POR ESTA VERSÃO CORRIGIDA:
int confirmacao = JOptionPane.showConfirmDialog(this, "Deseja excluir permanentemente este fornecedor?", "Confirmar Exclusão", JOptionPane.YES_NO_OPTION);


    if (confirmacao == JOptionPane.YES_OPTION) {
        try {
            // Proteção do índice para quando a tabela estiver filtrada/pesquisada
            int linhaRealDoModelo = tblFornecedores.convertRowIndexToModel(linhaSelecionada);
            
            // 1. Captura o ID do fornecedor na coluna 0 da tabela
            int idFornecedor = Integer.parseInt(tblFornecedores.getModel().getValueAt(linhaRealDoModelo, 0).toString());
            
            // 2. Chama o DAO correto do Fornecedor para executar a exclusão
            model.FornecedorDAO dao = new model.FornecedorDAO();
            dao.excluir(idFornecedor);

            JOptionPane.showMessageDialog(this, "Fornecedor excluído com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            preencherTabela(); // Atualiza a tabela para remover o registro visualmente

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao excluir fornecedor:\n" + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

        
    }//GEN-LAST:event_btnExcluirFornecedorActionPerformed

    private void btnVoltarTelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarTelaInicialActionPerformed
             TelaInicial telaInicial = new TelaInicial(this.usuarioLogado);
        telaInicial.setLocationRelativeTo(null);
        telaInicial.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVoltarTelaInicialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ListagemFornecedores(null).setVisible(true));
    }
    
        private void preencherTabela() {
        javax.swing.table.DefaultTableModel modeloTabela = (javax.swing.table.DefaultTableModel) tblFornecedores.getModel();
        modeloTabela.setNumRows(0); 

        FornecedorDAO dao = new FornecedorDAO();
        List<Fornecedor> lista = dao.listarTodos();

        // Instanciamos o TelefoneDAO para ler os números da empresa no laço
        TelefoneDAO telDAO = new TelefoneDAO();

        for (Fornecedor f : lista) {
            String statusAtivo = f.isAtivo() ? "Ativo" : "Inativo";

            // Busca e formata os múltiplos telefones do fornecedor
            List<Telefone> telefonesDoForn = telDAO.buscarPorFornecedor(f.getIdFornecedor()); 
            StringBuilder textoTelefones = new StringBuilder();
            
            for (Telefone t : telefonesDoForn) {
                if (textoTelefones.length() > 0) {
                    textoTelefones.append(" | ");
                }
                textoTelefones.append("(").append(t.getDdd()).append(") ").append(t.getTelefone());
            }
            
            String telefonesExibicao = (textoTelefones.length() == 0) ? "Sem telefone" : textoTelefones.toString();

            // Adiciona as colunas na ordem exata configurada no JTable
            modeloTabela.addRow(new Object[]{
                f.getIdFornecedor(),      // Coluna 0
                f.getRazaoSocial(),       // Coluna 1
                f.getCnpj(),              // Coluna 2
                f.getPessoaDeContato(),   // Coluna 3
                telefonesExibicao,        // Coluna 4 (Mostra todos os números amarrados)
                statusAtivo               // Coluna 5
            });
        }
    }
        
            private void filtrarTabela() {
        // Substitua pelo nome correto da sua caixa de texto de pesquisa se for diferente
        String texto = txtFornecedorPesquisar.getText().trim();

        if (texto.isEmpty()) {
            sorter.setRowFilter(null); // Remove o filtro se o campo estiver vazio
        } else {
            // Filtra ignorando maiúsculas e minúsculas (?i) buscando na coluna 1 (Nome)
            sorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + texto, 1));
        }
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastroFornecedor;
    private javax.swing.JButton btnExcluirFornecedor;
    private javax.swing.JButton btnPesquisarNome;
    private javax.swing.JButton btnVoltarTelaInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFornecedores;
    private javax.swing.JTextField txtFornecedorPesquisar;
    // End of variables declaration//GEN-END:variables
}
