package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.util.List;
import model.Cliente;
import model.ClienteDAO;
import model.Usuario;

public class ListagemClientes extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ListagemClientes.class.getName());
    private javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> sorter;
    private Usuario usuarioLogado;

    /**
     * Creates new form ListagemClientes
     */
    public ListagemClientes(Usuario usuario) {
        this.usuarioLogado = usuario;
        initComponents();

        jScrollPane1.setViewportView(tblClientes);
        preencherTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtClientePesquisar = new javax.swing.JTextField();
        btnPesquisarNome = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btnCadastroCliente = new javax.swing.JButton();
        btnExcluirCliente = new javax.swing.JButton();
        btnVoltarTelaInicial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Clientes");

        jLabel2.setText("Nome do Cliente:");

        txtClientePesquisar.addActionListener(this::txtClientePesquisarActionPerformed);
        txtClientePesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtClientePesquisarKeyReleased(evt);
            }
        });

        btnPesquisarNome.setText("PESQUISAR");
        btnPesquisarNome.addActionListener(this::btnPesquisarNomeActionPerformed);

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "CPF", "Telefone", "Data Cadastro", "Ativo(VIP)"
            }
        ));
        jScrollPane1.setViewportView(tblClientes);

        btnCadastroCliente.setText("+ NOVO");
        btnCadastroCliente.addActionListener(this::btnCadastroClienteActionPerformed);

        btnExcluirCliente.setText("EXCLUIR");
        btnExcluirCliente.addActionListener(this::btnExcluirClienteActionPerformed);

        btnVoltarTelaInicial.setText("TELA INICIAL");
        btnVoltarTelaInicial.addActionListener(this::btnVoltarTelaInicialActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtClientePesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(btnPesquisarNome)))
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnCadastroCliente)
                .addGap(133, 133, 133)
                .addComponent(btnExcluirCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltarTelaInicial)
                .addGap(137, 137, 137))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtClientePesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarNome))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastroCliente)
                    .addComponent(btnExcluirCliente)
                    .addComponent(btnVoltarTelaInicial))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtClientePesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClientePesquisarActionPerformed

    }//GEN-LAST:event_txtClientePesquisarActionPerformed

    private void btnCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroClienteActionPerformed

        CadastroCliente telaCadastro = new CadastroCliente(this.usuarioLogado);
        telaCadastro.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnCadastroClienteActionPerformed

    private void btnExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirClienteActionPerformed

        int linhaSelecionada = tblClientes.getSelectedRow();

        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione um cliente na tabela para excluir.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirmacao = JOptionPane.showConfirmDialog(this, "Deseja excluir permanentemente este cliente?", "Confirmar Exclusão", JOptionPane.YES_NO_OPTION);

        if (confirmacao == JOptionPane.YES_OPTION) {
            try {

                int linhaRealDoModelo = tblClientes.convertRowIndexToModel(linhaSelecionada);
                int idCliente = Integer.parseInt(tblClientes.getModel().getValueAt(linhaRealDoModelo, 0).toString());
                model.ClienteDAO dao = new model.ClienteDAO();
                dao.excluir(idCliente);

                JOptionPane.showMessageDialog(this, "Cliente excluído com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                preencherTabela();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao excluir cliente:\n" + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnExcluirClienteActionPerformed

    private void btnVoltarTelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarTelaInicialActionPerformed

        TelaInicial telaInicial = new TelaInicial(this.usuarioLogado);
        telaInicial.setLocationRelativeTo(null);
        telaInicial.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnVoltarTelaInicialActionPerformed

    private void btnPesquisarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarNomeActionPerformed

        filtrarTabela();

    }//GEN-LAST:event_btnPesquisarNomeActionPerformed

    private void txtClientePesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtClientePesquisarKeyReleased

        String termoBusca = txtClientePesquisar.getText().trim();

        ClienteDAO dao = new ClienteDAO();
        List<Cliente> listaFiltrada;

        if (termoBusca.isEmpty()) {
            listaFiltrada = dao.listarTodos();
        } else {
            listaFiltrada = dao.pesquisarPorNome(termoBusca);
        }

        DefaultTableModel modelo = (DefaultTableModel) tblClientes.getModel();

        modelo.setNumRows(0);

        for (Cliente c : listaFiltrada) {
            String statusAtivo = c.isAtivo() ? "Ativo" : "Inativo";

            modelo.addRow(new Object[]{
                c.getIdCliente(),
                c.getNomeCliente(),
                c.getCpf(),
                c.getTelefonesFormatados(),
                c.getDataCadastro(),
                statusAtivo
            });
        }
    }//GEN-LAST:event_txtClientePesquisarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ListagemClientes(null).setVisible(true));
    }

    private void preencherTabela() {
        DefaultTableModel modeloTabela = (DefaultTableModel) tblClientes.getModel();
        modeloTabela.setNumRows(0);

        ClienteDAO dao = new ClienteDAO();

        List<Cliente> lista = dao.listarTodos();

        for (Cliente c : lista) {
            String statusAtivo = c.isAtivo() ? "Ativo" : "Inativo";

            String telefonesExibicao = c.getTelefonesFormatados();

            modeloTabela.addRow(new Object[]{
                c.getIdCliente(),
                c.getNomeCliente(),
                c.getCpf(),
                telefonesExibicao,
                c.getDataCadastro(),
                statusAtivo
            });
        }

        sorter = new TableRowSorter<>(modeloTabela);
        tblClientes.setRowSorter(sorter);
    }

    private void filtrarTabela() {

        String texto = txtClientePesquisar.getText().trim();

        if (texto.isEmpty()) {
            sorter.setRowFilter(null);
        } else {

            sorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + texto, 1));
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastroCliente;
    private javax.swing.JButton btnExcluirCliente;
    private javax.swing.JButton btnPesquisarNome;
    private javax.swing.JButton btnVoltarTelaInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtClientePesquisar;
    // End of variables declaration//GEN-END:variables
}
