package view;

import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.util.List;
import model.Produto;
import model.ProdutoDAO;

/**
 *
 * @author karen
 */
public class ListagemProdutos extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ListagemProdutos.class.getName());
    private javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> sorter;
    private model.Usuario usuarioLogado;

    /**
     * Creates new form ListagemProdutos
     */
    public ListagemProdutos(model.Usuario usuario) {
        this.usuarioLogado = usuario;
        initComponents();

        jScrollPane1.setViewportView(tblProdutos);
        preencherTabela();
    }

    private void preencherTabela() {
        DefaultTableModel modeloTabela = (DefaultTableModel) tblProdutos.getModel(); // Pegue o modelo da sua JTable
        modeloTabela.setNumRows(0); // Limpa as linhas antigas para não duplicar dados

        // Puxa a lista direto do banco de dados através do DAO conectado
        ProdutoDAO dao = new ProdutoDAO();
        List<Produto> lista = dao.listarTodos();

        // Varre a lista de produtos montando o array para a tabela gráfica
        for (Produto p : lista) {
            String statusAtivo = p.isAtivo() ? "Ativo" : "Inativo";

            // Texto do fornecedor amigável (como ainda não fizemos JOIN, mostra o ID)
            String fornecedorExibicao = (p.getFkFornecedor() == 0) ? "Sem fornecedor" : "ID Fornecedor: " + p.getFkFornecedor();

            // Adiciona a linha respeitando a ordem das colunas da sua tabela
            // IMPORTANTE: Configure sua JTable no NetBeans para possuir de 5 a 6 colunas!
            modeloTabela.addRow(new Object[]{
                p.getIdProduto(), // Coluna 0 (ID)
                p.getNomeProduto(), // Coluna 1 (Nome)
                p.getDescricao(), // Coluna 2 (Descrição)
                String.format("R$ %.2f", p.getPrecoVenda()), // Coluna 3 (Preço formatado)
                p.getEstoqueAtual(), // Coluna 4 (Quantidade em estoque)
                p.isAtivo() ? "Ativo" : "Inativo",
                (p.getFkFornecedor() == 0) ? "Sem fornecedor" : "ID: " + p.getFkFornecedor()// Coluna 5 (Status)
            });
        }
        sorter = new TableRowSorter<>(modeloTabela);
        tblProdutos.setRowSorter(sorter);

    }

    /**
     *
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtProdutoPesquisar = new javax.swing.JTextField();
        btnPesquisarNome = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        btnCadastroProduto = new javax.swing.JButton();
        btnExcluirProduto = new javax.swing.JButton();
        btnVoltarTelaInicial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Produtos");

        jLabel2.setText("Nome do Produto:");

        txtProdutoPesquisar.addActionListener(this::txtProdutoPesquisarActionPerformed);
        txtProdutoPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProdutoPesquisarKeyReleased(evt);
            }
        });

        btnPesquisarNome.setText("PESQUISAR");
        btnPesquisarNome.addActionListener(this::btnPesquisarNomeActionPerformed);

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Produto", "Descrição", "Preço", "Estoque", "Ativo", "Fornecedor"
            }
        ));
        jScrollPane1.setViewportView(tblProdutos);

        btnCadastroProduto.setText("+ NOVO");
        btnCadastroProduto.addActionListener(this::btnCadastroProdutoActionPerformed);

        btnExcluirProduto.setText("EXCLUIR");
        btnExcluirProduto.addActionListener(this::btnExcluirProdutoActionPerformed);

        btnVoltarTelaInicial.setText("TELA INICIAL");
        btnVoltarTelaInicial.addActionListener(this::btnVoltarTelaInicialActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnCadastroProduto)
                .addGap(133, 133, 133)
                .addComponent(btnExcluirProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltarTelaInicial)
                .addGap(137, 137, 137))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtProdutoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(btnPesquisarNome))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtProdutoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarNome))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastroProduto)
                    .addComponent(btnExcluirProduto)
                    .addComponent(btnVoltarTelaInicial))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtProdutoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdutoPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdutoPesquisarActionPerformed

    private void btnPesquisarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarNomeActionPerformed

        // Substitua a linha 143 por isto:
        String texto = txtProdutoPesquisar.getText().trim(); // Mude txtPesquisa para o nome do seu campo de busca se for diferente
        if (texto.length() == 0) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + texto, 1)); // Filtra pelo Nome na Coluna 1
        }

    }//GEN-LAST:event_btnPesquisarNomeActionPerformed

    private void btnCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroProdutoActionPerformed

        CadastroProduto telaCadastro = new CadastroProduto(this.usuarioLogado);

        // 2. Centraliza a tela de cadastro no meio do monitor
        telaCadastro.setLocationRelativeTo(null);

        // 3. Torna a tela de cadastro visível
        telaCadastro.setVisible(true);
        this.dispose(); // Fecha a tela de listagem atual
    }//GEN-LAST:event_btnCadastroProdutoActionPerformed

    private void btnExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirProdutoActionPerformed

        // 1. Verifica se o usuário selecionou uma linha na JTable
        int linhaSelecionada = tblProdutos.getSelectedRow();

        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione um produto na tabela para excluir.");
            return;
        }

        // 2. Pergunta se o usuário tem certeza (Boa prática de UX)
        int confirmar = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir este produto?", "Confirmar Exclusão", JOptionPane.YES_NO_OPTION);

        if (confirmar == JOptionPane.YES_OPTION) {
            // 3. Pega o ID da primeira coluna (índice 0) da linha selecionada
            int idProduto = (int) tblProdutos.getValueAt(linhaSelecionada, 0);

            // 4. Executa a exclusão através do seu ProdutoDAO
            ProdutoDAO dao = new ProdutoDAO();
            dao.excluir(idProduto);

            // 5. Atualiza a tabela na tela para sumir com o produto deletado
            preencherTabela();
            JOptionPane.showMessageDialog(this, "Produto excluído com sucesso!");
        }


    }//GEN-LAST:event_btnExcluirProdutoActionPerformed

    private void btnVoltarTelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarTelaInicialActionPerformed
        TelaInicial telaInicial = new TelaInicial(this.usuarioLogado);
        telaInicial.setLocationRelativeTo(null);
        telaInicial.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnVoltarTelaInicialActionPerformed

    private void txtProdutoPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProdutoPesquisarKeyReleased

        String termoBusca = txtProdutoPesquisar.getText().trim();

        ProdutoDAO dao = new ProdutoDAO();
        List<Produto> listaFiltrada;

        // Se o campo estiver vazio, traz tudo. Se tiver texto, filtra.
        if (termoBusca.isEmpty()) {
            listaFiltrada = dao.listarTodos();
        } else {
            listaFiltrada = dao.pesquisarPorNome(termoBusca);
        }

        // Atualiza a JTable apenas com o resultado do filtro
        DefaultTableModel modelo = (DefaultTableModel) tblProdutos.getModel();
        modelo.setNumRows(0);

        for (Produto p : listaFiltrada) {
        // DEIXE O SEU LAÇO FOR ASSIM:

    String statusAtivo = p.isAtivo() ? "Ativo" : "Inativo";

    modelo.addRow(new Object[]{
        p.getIdProduto(),
        p.getNomeProduto(),
        p.getDescricao(),
        String.format("R$ %.2f", p.getPrecoVenda()), // Mantém o preço formatado
        p.getEstoqueAtual(),
        statusAtivo // Mantém o padrão "Ativo"/"Inativo"
    });
}

    

    }//GEN-LAST:event_txtProdutoPesquisarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ListagemProdutos(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastroProduto;
    private javax.swing.JButton btnExcluirProduto;
    private javax.swing.JButton btnPesquisarNome;
    private javax.swing.JButton btnVoltarTelaInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtProdutoPesquisar;
    // End of variables declaration//GEN-END:variables
}
