package view;

import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.util.List;
import model.Produto;
import model.ProdutoDAO;

public class ListagemProdutos extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ListagemProdutos.class.getName());
    private javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> sorter;
    private model.Usuario usuarioLogado;

    public ListagemProdutos(model.Usuario usuario) {
        this.usuarioLogado = usuario;
        initComponents();

        jScrollPane1.setViewportView(tblProdutos);
        preencherTabela();
    }

    private void preencherTabela() {
        DefaultTableModel modeloTabela = (DefaultTableModel) tblProdutos.getModel();
        modeloTabela.setNumRows(0);

        ProdutoDAO dao = new ProdutoDAO();
        List<Produto> lista = dao.listarTodos();

        for (Produto p : lista) {
            String statusAtivo = p.isAtivo() ? "Ativo" : "Inativo";

            String fornecedorExibicao = (p.getFkFornecedor() == 0) ? "Sem fornecedor" : "ID Fornecedor: " + p.getFkFornecedor();

            modeloTabela.addRow(new Object[]{
                p.getIdProduto(),
                p.getNomeProduto(),
                p.getDescricao(),
                String.format("R$ %.2f", p.getPrecoVenda()),
                p.getEstoqueAtual(),
                p.isAtivo() ? "Ativo" : "Inativo",
                (p.getFkFornecedor() == 0) ? "Sem fornecedor" : "ID: " + p.getFkFornecedor()
            });
        }
        sorter = new TableRowSorter<>(modeloTabela);
        tblProdutos.setRowSorter(sorter);
    }

    /**
     *
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtProdutoPesquisar = new javax.swing.JTextField();
        btnPesquisarNome = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        btnCadastroProduto = new javax.swing.JButton();
        btnExcluirProduto = new javax.swing.JButton();
        btnVoltarTelaInicial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Produtos");

        jLabel2.setText("Nome do Produto:");

        txtProdutoPesquisar.addActionListener(this::txtProdutoPesquisarActionPerformed);
        txtProdutoPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtProdutoPesquisarKeyReleased(evt);
            }
        });

        btnPesquisarNome.setText("PESQUISAR");
        btnPesquisarNome.addActionListener(this::btnPesquisarNomeActionPerformed);

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Produto", "Descrição", "Preço", "Estoque", "Ativo", "Fornecedor"
            }
        ));
        jScrollPane1.setViewportView(tblProdutos);

        btnCadastroProduto.setText("+ NOVO");
        btnCadastroProduto.addActionListener(this::btnCadastroProdutoActionPerformed);

        btnExcluirProduto.setText("EXCLUIR");
        btnExcluirProduto.addActionListener(this::btnExcluirProdutoActionPerformed);

        btnVoltarTelaInicial.setText("TELA INICIAL");
        btnVoltarTelaInicial.addActionListener(this::btnVoltarTelaInicialActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnCadastroProduto)
                .addGap(133, 133, 133)
                .addComponent(btnExcluirProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltarTelaInicial)
                .addGap(137, 137, 137))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtProdutoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(btnPesquisarNome))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtProdutoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarNome))
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastroProduto)
                    .addComponent(btnExcluirProduto)
                    .addComponent(btnVoltarTelaInicial))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtProdutoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdutoPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdutoPesquisarActionPerformed

    private void btnPesquisarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarNomeActionPerformed

        String texto = txtProdutoPesquisar.getText().trim();
        if (texto.length() == 0) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + texto, 1));
        }
    }//GEN-LAST:event_btnPesquisarNomeActionPerformed

    private void btnCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroProdutoActionPerformed

        CadastroProduto telaCadastro = new CadastroProduto(this.usuarioLogado);
        telaCadastro.setLocationRelativeTo(null);
        telaCadastro.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnCadastroProdutoActionPerformed

    private void btnExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirProdutoActionPerformed

        int linhaSelecionada = tblProdutos.getSelectedRow();

        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione um produto na tabela para excluir.");
            return;
        }

        int confirmar = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir este produto?", "Confirmar Exclusão", JOptionPane.YES_NO_OPTION);

        if (confirmar == JOptionPane.YES_OPTION) {

            int idProduto = (int) tblProdutos.getValueAt(linhaSelecionada, 0);

            ProdutoDAO dao = new ProdutoDAO();
            dao.excluir(idProduto);

            preencherTabela();
            JOptionPane.showMessageDialog(this, "Produto excluído com sucesso!");
        }
    }//GEN-LAST:event_btnExcluirProdutoActionPerformed

    private void btnVoltarTelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarTelaInicialActionPerformed

        TelaInicial telaInicial = new TelaInicial(this.usuarioLogado);
        telaInicial.setLocationRelativeTo(null);
        telaInicial.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnVoltarTelaInicialActionPerformed

    private void txtProdutoPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProdutoPesquisarKeyReleased

        String termoBusca = txtProdutoPesquisar.getText().trim();

        ProdutoDAO dao = new ProdutoDAO();
        List<Produto> listaFiltrada;

        if (termoBusca.isEmpty()) {
            listaFiltrada = dao.listarTodos();
        } else {
            listaFiltrada = dao.pesquisarPorNome(termoBusca);
        }

        DefaultTableModel modelo = (DefaultTableModel) tblProdutos.getModel();
        modelo.setNumRows(0);

        for (Produto p : listaFiltrada) {

            String statusAtivo = p.isAtivo() ? "Ativo" : "Inativo";

            modelo.addRow(new Object[]{
                p.getIdProduto(),
                p.getNomeProduto(),
                p.getDescricao(),
                String.format("R$ %.2f", p.getPrecoVenda()),
                p.getEstoqueAtual(),
                statusAtivo
            });
        }
    }//GEN-LAST:event_txtProdutoPesquisarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ListagemProdutos(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastroProduto;
    private javax.swing.JButton btnExcluirProduto;
    private javax.swing.JButton btnPesquisarNome;
    private javax.swing.JButton btnVoltarTelaInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtProdutoPesquisar;
    // End of variables declaration//GEN-END:variables
}
