package view;

import javax.swing.JOptionPane;
import model.FuncionarioDAO;
import model.Funcionario;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.text.SimpleDateFormat;
import javax.swing.table.TableRowSorter;
import model.Usuario;

public class ListagemFuncionarios extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ListagemFuncionarios.class.getName());
    private javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> sorter;
    private Usuario usuarioLogado;

    /**
     * Creates new form ListagemFuncionarios
     */
    public ListagemFuncionarios(Usuario usuario) {
        this.usuarioLogado = usuario;
        initComponents();
        jScrollPane1.setViewportView(tblFuncionarios);
        preencherTabela();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFuncionarioPesquisarPorNome = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFuncionarios = new javax.swing.JTable();
        btnCadastrarFunc = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnTelaInicial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Funcionários");

        jLabel2.setText("Nome do funcionário:");

        txtFuncionarioPesquisarPorNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFuncionarioPesquisarPorNomeKeyReleased(evt);
            }
        });

        btnPesquisar.setText("PESQUISAR");
        btnPesquisar.addActionListener(this::btnPesquisarActionPerformed);

        tblFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "CPF", "Função", "Telefone", "Valor do Serviço", "Ativo"
            }
        ));
        jScrollPane1.setViewportView(tblFuncionarios);

        btnCadastrarFunc.setText("+ NOVO");
        btnCadastrarFunc.addActionListener(this::btnCadastrarFuncActionPerformed);

        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(this::btnExcluirActionPerformed);

        btnTelaInicial.setText("TELA INICIAL");
        btnTelaInicial.addActionListener(this::btnTelaInicialActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2)
                        .addGap(65, 65, 65)
                        .addComponent(txtFuncionarioPesquisarPorNome, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btnPesquisar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnCadastrarFunc)
                        .addGap(127, 127, 127)
                        .addComponent(btnExcluir)
                        .addGap(112, 112, 112)
                        .addComponent(btnTelaInicial)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFuncionarioPesquisarPorNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarFunc)
                    .addComponent(btnExcluir)
                    .addComponent(btnTelaInicial))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaInicialActionPerformed

        TelaInicial telaInicial = new TelaInicial(this.usuarioLogado);
        telaInicial.setLocationRelativeTo(null);
        telaInicial.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnTelaInicialActionPerformed

    private void btnCadastrarFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarFuncActionPerformed

        CadastroFuncionario telaCadastro = new CadastroFuncionario(this.usuarioLogado);
        telaCadastro.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnCadastrarFuncActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

        int linhaSelecionada = tblFuncionarios.getSelectedRow();

        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione um funcionário na tabela para excluir.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirmacao = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir permanentemente este funcionário?", "Confirmar Exclusão", JOptionPane.YES_NO_OPTION);

        if (confirmacao == JOptionPane.YES_OPTION) {
            try {

                int linhaRealDoModelo = tblFuncionarios.convertRowIndexToModel(linhaSelecionada);
                int idFuncionario = Integer.parseInt(tblFuncionarios.getModel().getValueAt(linhaRealDoModelo, 0).toString());

                FuncionarioDAO dao = new FuncionarioDAO();
                dao.excluir(idFuncionario);

                JOptionPane.showMessageDialog(this, "Funcionário excluído com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);

                preencherTabela();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao excluir funcionário:\n" + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed

        filtrarTabela();

    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txtFuncionarioPesquisarPorNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFuncionarioPesquisarPorNomeKeyReleased

        filtrarTabela();

    }//GEN-LAST:event_txtFuncionarioPesquisarPorNomeKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ListagemFuncionarios(null).setVisible(true));
    }

    private void preencherTabela() {
        DefaultTableModel modeloTabela = (DefaultTableModel) tblFuncionarios.getModel();
        modeloTabela.setNumRows(0);

        FuncionarioDAO dao = new FuncionarioDAO();
        List<Funcionario> lista = dao.listarTodos();

        SimpleDateFormat formatoData = new SimpleDateFormat("dd/MM/yyyy");

        model.TelefoneDAO telDAO = new model.TelefoneDAO();

        for (Funcionario f : lista) {
            String dataNascFormatada = (f.getDataNascimento() != null) ? formatoData.format(f.getDataNascimento()) : "";
            String statusAtivo = f.isAtivo() ? "Sim" : "Não";

            List<model.Telefone> telefonesDoFunc = telDAO.buscarPorFuncionario(f.getIdFuncionario());
            StringBuilder textoTelefones = new StringBuilder();

            for (model.Telefone t : telefonesDoFunc) {
                if (textoTelefones.length() > 0) {
                    textoTelefones.append(" | ");
                }

                textoTelefones.append("(").append(t.getDdd()).append(") ").append(t.getTelefone());
            }

            String telefonesExibicao = (textoTelefones.length() == 0) ? "Sem telefone" : textoTelefones.toString();

            String enderecoExibicao = (f.getFkEndereco() == 0) ? "Sem endereço" : "Cadastrado (ID: " + f.getFkEndereco() + ")";

            modeloTabela.addRow(new Object[]{
                f.getIdFuncionario(),
                f.getNomeFuncionario(),
                f.getCpf(),
                f.getFuncao(),
                telefonesExibicao,
                String.format("R$ %.2f", f.getValorDoServico()),
                statusAtivo
            });
        }

        sorter = new TableRowSorter<>(modeloTabela);
        tblFuncionarios.setRowSorter(sorter);
    }

    private void filtrarTabela() {
        String texto = txtFuncionarioPesquisarPorNome.getText().trim();

        if (texto.isEmpty()) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + texto, 1));
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarFunc;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnTelaInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFuncionarios;
    private javax.swing.JTextField txtFuncionarioPesquisarPorNome;
    // End of variables declaration//GEN-END:variables
}
