package view;

/**
 *
 * @author karen
 */
public class Relatorio extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Relatorio.class.getName());

    /**
     * Creates new form Relatorio
     */
    public Relatorio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnClienteServico = new javax.swing.JButton();
        btnEntradasSaidas = new javax.swing.JButton();
        btnEstoque = new javax.swing.JButton();
        btnVoltarRelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Relatórios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 36)); // NOI18N
        jLabel1.setText("Instituto da Beleza");

        btnClienteServico.setBackground(new java.awt.Color(255, 255, 0));
        btnClienteServico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnClienteServico.setText("Clientes e Serviços");
        btnClienteServico.setToolTipText("Salários e pagamentos");
        btnClienteServico.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnClienteServico.addActionListener(this::btnClienteServicoActionPerformed);

        btnEntradasSaidas.setBackground(new java.awt.Color(255, 255, 0));
        btnEntradasSaidas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEntradasSaidas.setText("Fluxo de caixa diário");
        btnEntradasSaidas.setToolTipText("Pagamentos feitos e recebidos");
        btnEntradasSaidas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEntradasSaidas.addActionListener(this::btnEntradasSaidasActionPerformed);

        btnEstoque.setBackground(new java.awt.Color(255, 255, 0));
        btnEstoque.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEstoque.setText("Estoque");
        btnEstoque.setToolTipText("Controle de estoque");
        btnEstoque.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEstoque.addActionListener(this::btnEstoqueActionPerformed);

        btnVoltarRelatorio.setBackground(new java.awt.Color(255, 255, 0));
        btnVoltarRelatorio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVoltarRelatorio.setText("Voltar");
        btnVoltarRelatorio.setToolTipText("Volta para a tela inicial");
        btnVoltarRelatorio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVoltarRelatorio.addActionListener(this::btnVoltarRelatorioActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClienteServico)
                    .addComponent(btnEntradasSaidas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEstoque, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnVoltarRelatorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jLabel1)
                .addGap(0, 27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntradasSaidas)
                    .addComponent(btnEstoque))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClienteServico)
                    .addComponent(btnVoltarRelatorio))
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarRelatorioActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarRelatorioActionPerformed

    private void btnEntradasSaidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradasSaidasActionPerformed
      /*
        EmConstrucao exclui = new EmConstrucao();
        exclui.setVisible(true);
        */
    }//GEN-LAST:event_btnEntradasSaidasActionPerformed

    private void btnEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstoqueActionPerformed
     /*   EmConstrucao exclui = new EmConstrucao();
        exclui.setVisible(true);
        */
    }//GEN-LAST:event_btnEstoqueActionPerformed

    private void btnClienteServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteServicoActionPerformed
     /*   EmConstrucao exclui = new EmConstrucao();
        exclui.setVisible(true);
        */
    }//GEN-LAST:event_btnClienteServicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Relatorio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClienteServico;
    private javax.swing.JButton btnEntradasSaidas;
    private javax.swing.JButton btnEstoque;
    private javax.swing.JButton btnVoltarRelatorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
