package view;

public class TelaAgenda extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaAgenda.class.getName());
    private model.Usuario usuarioLogado;

    public TelaAgenda(model.Usuario usuario) {
        this.usuarioLogado = usuario;
        initComponents();

        cbServico.removeAllItems();
        carregarCombosDoBanco();
        atualizarTabelaAgenda();

        configurarPermissoesAgenda();
    }

    private void configurarPermissoesAgenda() {

        if (usuarioLogado.getPerfil().equalsIgnoreCase("funcionario")) {

            btnExcluirAgendamento.setEnabled(false);

            logger.info("Botão de exclusão desativado para o funcionário: " + usuarioLogado.getLogin());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        btnAgendar = new javax.swing.JButton();
        btnCadastrarCliente = new javax.swing.JButton();
        btnVoltarTPrincipal = new javax.swing.JButton();
        btnExcluirAgendamento = new javax.swing.JButton();
        lblAgenda = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblServico = new javax.swing.JLabel();
        lblProfissional = new javax.swing.JLabel();
        lblKitServico = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        cbServico = new javax.swing.JComboBox<>();
        cbProfissional = new javax.swing.JComboBox<>();
        cbKitServico = new javax.swing.JComboBox<>();
        lblHorario = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        txtData = new javax.swing.JTextField();
        txtHorario = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agenda Semanal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        lblTitulo.setFont(new java.awt.Font("Yu Gothic Medium", 1, 14)); // NOI18N
        lblTitulo.setText("Instituto da Beleza");

        btnAgendar.setBackground(new java.awt.Color(255, 255, 0));
        btnAgendar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAgendar.setText("Agendar");
        btnAgendar.setToolTipText("Limpa o formulário");
        btnAgendar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAgendar.addActionListener(this::btnAgendarActionPerformed);

        btnCadastrarCliente.setBackground(new java.awt.Color(255, 255, 0));
        btnCadastrarCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCadastrarCliente.setText("Cadastrar Cliente");
        btnCadastrarCliente.setToolTipText("Cadastro de Cliente");
        btnCadastrarCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCadastrarCliente.addActionListener(this::btnCadastrarClienteActionPerformed);

        btnVoltarTPrincipal.setBackground(new java.awt.Color(255, 255, 0));
        btnVoltarTPrincipal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnVoltarTPrincipal.setText("Voltar");
        btnVoltarTPrincipal.setToolTipText("Volta para a tela principal");
        btnVoltarTPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVoltarTPrincipal.addActionListener(this::btnVoltarTPrincipalActionPerformed);

        btnExcluirAgendamento.setBackground(new java.awt.Color(255, 255, 0));
        btnExcluirAgendamento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnExcluirAgendamento.setText("Excluir agendamento");
        btnExcluirAgendamento.setToolTipText("Volta para a tela principal");
        btnExcluirAgendamento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnExcluirAgendamento.addActionListener(this::btnExcluirAgendamentoActionPerformed);

        lblAgenda.setText("Agenda semanal");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        lblServico.setText("Serviço:");

        lblProfissional.setText("Profissional:");

        lblKitServico.setText("Kit Serviço:");

        lblData.setText("Data:");

        cbServico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha o serviço", "Cabelo corte", "Cabelo hidratação", "Cabelo tintura", "Cabelo escova", "Depilação completa", "Depilação partes", "Manicure pé", "Manicure mão", "Manicure pé e mão", "Maquiagem" }));

        cbProfissional.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione o funcionário da sua preferência", "Cabelereiro", "Depilador", "Manicure" }));

        cbKitServico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Qual o kit de serviços a ser usado", "Kit completo cabelo hidratação", "Só aplicar hidratação", "Kit completo depilação", "Só depilar", "Kit completo Maquilagem", "Só maquiar", "Kit completo corte", "Kit completo tintura", "Só tintura", "Kit manicure ou pedicure", "Kit manicure e pedicure", " " }));

        lblHorario.setText("Horário:");

        lblCliente.setText("Cliente:");

        btnLimpar.setBackground(new java.awt.Color(255, 255, 0));
        btnLimpar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.setToolTipText("Volta para a tela principal");
        btnLimpar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLimpar.addActionListener(this::btnLimparActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCadastrarCliente)
                        .addGap(18, 18, 18)
                        .addComponent(btnAgendar, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnExcluirAgendamento, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnVoltarTPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 772, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAgenda)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblProfissional)
                            .addComponent(lblCliente)
                            .addComponent(lblData))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblKitServico)
                                    .addComponent(lblServico)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblHorario)))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cbServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72)
                                .addComponent(lblTitulo))
                            .addComponent(cbKitServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitulo)
                    .addComponent(lblCliente)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblServico)
                    .addComponent(cbServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProfissional)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbProfissional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblKitServico)
                        .addComponent(cbKitServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData)
                    .addComponent(lblHorario)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(lblAgenda)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrarCliente)
                    .addComponent(btnAgendar)
                    .addComponent(btnExcluirAgendamento)
                    .addComponent(btnVoltarTPrincipal)
                    .addComponent(btnLimpar))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcluirAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirAgendamentoActionPerformed

        if (usuarioLogado.getPerfil().equalsIgnoreCase("funcionario")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Operação não permitida! Funcionários não têm permissão para deletar agendamentos.",
                    "Acesso Restrito", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        int linhaSelecionada = jTable1.getSelectedRow();
        if (linhaSelecionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione um agendamento na tabela para remover.");
            return;
        }

        int linhaModelo = jTable1.convertRowIndexToModel(linhaSelecionada);

        try {

            int idAgenda = Integer.parseInt(jTable1.getModel().getValueAt(linhaModelo, 0).toString());
            String dataAtendimento = jTable1.getModel().getValueAt(linhaModelo, 1).toString();
            String clienteNome = jTable1.getModel().getValueAt(linhaModelo, 3).toString();

            int confirmar = javax.swing.JOptionPane.showConfirmDialog(this,
                    "Tem certeza que deseja desmarcar o agendamento de '" + clienteNome + "' marcado para " + dataAtendimento + "?",
                    "Confirmar Cancelamento", javax.swing.JOptionPane.YES_NO_OPTION);

            if (confirmar == javax.swing.JOptionPane.YES_OPTION) {

                model.AgendaDAO daoAgenda = new model.AgendaDAO();
                daoAgenda.desmarcarAgendamento(idAgenda);

                javax.swing.JOptionPane.showMessageDialog(this, "Agendamento desmarcado com sucesso!");

                // 5. ATUALIZAÇÃO: Força a jTable1 a se redesenhar buscando os dados atualizados do MySQL
                atualizarTabelaAgenda();
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao remover agendamento: " + e.getMessage());
        }


    }//GEN-LAST:event_btnExcluirAgendamentoActionPerformed

    private void btnVoltarTPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarTPrincipalActionPerformed

        dispose();

    }//GEN-LAST:event_btnVoltarTPrincipalActionPerformed

    private void btnCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarClienteActionPerformed
        try {

            view.CadastroCliente telaCliente = new view.CadastroCliente(this.usuarioLogado);
            telaCliente.setVisible(true);
            telaCliente.setLocationRelativeTo(null);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao abrir a tela de cadastro de clientes: " + e.getMessage());
        }
    }//GEN-LAST:event_btnCadastrarClienteActionPerformed

    private void btnAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarActionPerformed
        try {

            String nomeCliente = txtNomeCliente.getText().trim();
            String dataDigitada = txtData.getText().trim();
            String horaDigitada = txtHorario.getText().trim();

            if (nomeCliente.isEmpty() || dataDigitada.contains("_") || horaDigitada.contains("_") || cbServico.getSelectedItem() == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Por favor, preencha o Nome, Data e Hora completos!");
                return;
            }

            model.ClienteDAO cDao = new model.ClienteDAO();
            if (!cDao.existeClientePorNome(nomeCliente)) {

                javax.swing.JOptionPane.showMessageDialog(this,
                        "Cliente '" + nomeCliente + "' não encontrado no sistema!\n"
                        + "Abrindo a tela de cadastro para registrar o cliente.",
                        "Cliente Não Encontrado", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }

            String[] partesData = dataDigitada.split("/");
            String dia = partesData[0].trim();
            String mes = partesData[1].trim();
            String ano = partesData[2].trim();

            String[] partesHora = horaDigitada.split(":");
            String hora = partesHora[0].trim();
            String minuto = partesHora[1].trim();

            String formatoDirectSQL = ano + "-" + mes + "-" + dia + " " + hora + ":" + minuto + ":00";

            java.sql.Timestamp dataHora;
            try {
                dataHora = java.sql.Timestamp.valueOf(formatoDirectSQL);
            } catch (IllegalArgumentException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Erro interno na conversão do tempo. Verifique os valores digitados!");
                return;
            }

            String textoServico = cbServico.getSelectedItem().toString();

            int idServico = -1;
            if (textoServico.contains("-")) {
                idServico = Integer.parseInt(textoServico.split("-")[0].trim());
            }

            if (idServico == -1) {
                javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione um serviço válido!");
                return;
            }

            double precoServico = 0.0;

            model.Cliente clienteFake = new model.Cliente();
            clienteFake.setIdCliente(1);

            model.Funcionario funcFake = new model.Funcionario();
            funcFake.setIdFuncionario(3);

            model.Servico servico = new model.Servico();
            servico.setIdServico(idServico);

            model.Agenda novaAgenda = new model.Agenda();
            novaAgenda.setDataHora(dataHora);
            novaAgenda.setCliente(clienteFake);
            novaAgenda.setFuncionario(funcFake);
            novaAgenda.setServico(servico);

            if (this.usuarioLogado != null) {
                novaAgenda.setUsuario(this.usuarioLogado);
            } else {
                model.Usuario userFake = new model.Usuario();
                userFake.setIdUsuario(3);
                novaAgenda.setUsuario(userFake);
            }

            novaAgenda.setStatus("marcado");
            novaAgenda.setPrecoServico(precoServico);
            novaAgenda.setValorProduto(0.0);
            novaAgenda.setDesconto(0.0);
            novaAgenda.setObservacao("Cliente: " + nomeCliente);

            model.AgendaDAO daoAgenda = new model.AgendaDAO();
            daoAgenda.inserir(novaAgenda);

            javax.swing.JOptionPane.showMessageDialog(this, "Agendamento de '" + nomeCliente + "' realizado com sucesso!");

            txtNomeCliente.setText("");
            txtData.setText("");
            txtHorario.setText("");
            cbServico.setSelectedIndex(0);

            atualizarTabelaAgenda();

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao agendar: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAgendarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed

        if (txtNomeCliente != null) {
            txtNomeCliente.setText("");
        }

        if (txtData != null) {
            txtData.setText("");
        }
        if (txtHorario != null) {
            txtHorario.setText("");
        }

        if (cbServico != null && cbServico.getItemCount() > 0) {
            cbServico.setSelectedIndex(0);
        }

        atualizarTabelaAgenda();

        if (txtNomeCliente != null) {
            txtNomeCliente.requestFocus();
        }
    }//GEN-LAST:event_btnLimparActionPerformed

    private void atualizarTabelaAgenda() {

        String[] colunas = {"ID Agenda", "Data", "Hora", "Cliente", "Serviço Realizado", "Status Atual"};

        javax.swing.table.DefaultTableModel modeloDefault = new javax.swing.table.DefaultTableModel(colunas, 0);

        jTable1.setAutoCreateColumnsFromModel(true);
        jTable1.setModel(modeloDefault);

        try {

            model.AgendaDAO daoAgenda = new model.AgendaDAO();
            java.util.List<model.Agenda> lista = daoAgenda.listarTodos();

            java.text.SimpleDateFormat formatadorData = new java.text.SimpleDateFormat("dd/MM/yyyy");
            java.text.SimpleDateFormat formatadorHora = new java.text.SimpleDateFormat("HH:mm");

            for (model.Agenda a : lista) {

                if (a.getStatus().equalsIgnoreCase("desmarcado")) {
                    continue;
                }

                String nomeExibirCliente = a.getCliente().getNomeCliente();
                if (a.getObservacao() != null && a.getObservacao().startsWith("Cliente: ")) {
                    nomeExibirCliente = a.getObservacao().replace("Cliente: ", "").trim();
                }

                String dataBrasil = "";
                String horaBrasil = "";
                if (a.getDataHora() != null) {
                    dataBrasil = formatadorData.format(a.getDataHora()); // Fica: "01/10/2026"
                    horaBrasil = formatadorHora.format(a.getDataHora()); // Fica: "22:14"
                }

                Object[] linha = {
                    a.getIdAgenda(),
                    dataBrasil,
                    horaBrasil,
                    nomeExibirCliente,
                    a.getServico().getServico(),
                    a.getStatus().toUpperCase()
                };

                modeloDefault.addRow(linha);
            }

            javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> sorterTabela = new javax.swing.table.TableRowSorter<>(modeloDefault);
            jTable1.setRowSorter(sorterTabela);

            if (jTable1.getColumnCount() >= 6) {
                jTable1.getColumnModel().getColumn(0).setMinWidth(0);
                jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
                jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao carregar a tabela de agendamentos: " + e.getMessage());
        }
    }

    private void carregarCombosDoBanco() {
        try {

            cbServico.removeAllItems();
            cbServico.addItem("Selecione um serviço...");

            model.ServicoDAO sDao = new model.ServicoDAO();
            java.util.List<model.Servico> lista = sDao.listarTodos();

            for (model.Servico s : lista) {
                cbServico.addItem(s.getIdServico() + " - " + s.getServico());
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Erro ao carregar serviços no menu: " + e.getMessage());
        }
    }

    private int obterIdCombo(javax.swing.JComboBox combo) {
        if (combo == null || combo.getSelectedItem() == null || combo.getSelectedItem().toString().startsWith("Selecione")) {
            return -1;
        }
        try {
            String item = combo.getSelectedItem().toString();
            return Integer.parseInt(item.split("-")[0].trim());
        } catch (Exception e) {
            return -1;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaAgenda(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendar;
    private javax.swing.JButton btnCadastrarCliente;
    private javax.swing.JButton btnExcluirAgendamento;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnVoltarTPrincipal;
    private javax.swing.JComboBox<String> cbKitServico;
    private javax.swing.JComboBox<String> cbProfissional;
    private javax.swing.JComboBox<String> cbServico;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAgenda;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblHorario;
    private javax.swing.JLabel lblKitServico;
    private javax.swing.JLabel lblProfissional;
    private javax.swing.JLabel lblServico;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtHorario;
    private javax.swing.JTextField txtNomeCliente;
    // End of variables declaration//GEN-END:variables
}
