package view;

import model.Usuario;

public class TelaInicial extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaInicial.class.getName());

    private Usuario usuarioLogado;

    public TelaInicial(Usuario usuario) {
        initComponents();
        this.usuarioLogado = usuario;
        if (usuario != null) {
            this.setTitle("Instituto da Beleza - Logado como: " + usuario.getLogin());
            configurarPermissoes();
        } else {
            this.setTitle("Instituto da Beleza - Usuário não identificado");
        }
        this.setTitle("Instituto da Beleza - Logado como: " + usuario.getLogin());

        configurarPermissoes();
    }

    private void configurarPermissoes() {
        if (usuarioLogado != null) {
            String perfil = usuarioLogado.getPerfil().toLowerCase();

            if (!perfil.equals("gerente")) {
                btnCadFunc.setEnabled(false);
                btnRelatorios.setEnabled(false);
                btnCadFunc.setToolTipText("Apenas gerentes podem acessar este recurso.");
                btnRelatorios.setToolTipText("Apenas gerentes podem acessar este recurso.");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCadCliente = new javax.swing.JButton();
        btnAgenda = new javax.swing.JButton();
        btnRelatorios = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnCadForn = new javax.swing.JButton();
        btnCadProd = new javax.swing.JButton();
        btnCadFunc = new javax.swing.JButton();
        btnKitServico = new javax.swing.JButton();
        btnKitServico1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tela  principal do instituto da beleza", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 36)); // NOI18N
        jLabel1.setText("Instituto da Beleza");

        btnCadCliente.setBackground(new java.awt.Color(255, 255, 0));
        btnCadCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCadCliente.setText("Clientes");
        btnCadCliente.setToolTipText("Cadastrar clientes");
        btnCadCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCadCliente.addActionListener(this::btnCadClienteActionPerformed);

        btnAgenda.setBackground(new java.awt.Color(255, 255, 0));
        btnAgenda.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAgenda.setText("Agenda");
        btnAgenda.setToolTipText("Entrar na agenda");
        btnAgenda.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAgenda.addActionListener(this::btnAgendaActionPerformed);

        btnRelatorios.setBackground(new java.awt.Color(255, 255, 0));
        btnRelatorios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRelatorios.setText("Relatórios");
        btnRelatorios.setToolTipText("Relatórios de produtos e serviços");
        btnRelatorios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRelatorios.addActionListener(this::btnRelatoriosActionPerformed);

        btnSair.setBackground(new java.awt.Color(255, 255, 0));
        btnSair.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSair.setText("SAIR");
        btnSair.setToolTipText("Sair do aplicativo");
        btnSair.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSair.addActionListener(this::btnSairActionPerformed);

        btnCadForn.setBackground(new java.awt.Color(255, 255, 0));
        btnCadForn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCadForn.setText("Fornecedores");
        btnCadForn.setToolTipText("Cadastrar fornecedor");
        btnCadForn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCadForn.addActionListener(this::btnCadFornActionPerformed);

        btnCadProd.setBackground(new java.awt.Color(255, 255, 0));
        btnCadProd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCadProd.setText("Produtos");
        btnCadProd.setToolTipText("Cadastrar produtos");
        btnCadProd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCadProd.addActionListener(this::btnCadProdActionPerformed);

        btnCadFunc.setBackground(new java.awt.Color(255, 255, 0));
        btnCadFunc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCadFunc.setText("Funcionários");
        btnCadFunc.setToolTipText("Cadastrar funcionários");
        btnCadFunc.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCadFunc.addActionListener(this::btnCadFuncActionPerformed);

        btnKitServico.setBackground(new java.awt.Color(255, 255, 0));
        btnKitServico.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnKitServico.setText("Serviços");
        btnKitServico.setToolTipText("Relatórios de produtos e serviços");
        btnKitServico.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKitServico.addActionListener(this::btnKitServicoActionPerformed);

        btnKitServico1.setBackground(new java.awt.Color(255, 255, 0));
        btnKitServico1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnKitServico1.setText("KitServiços");
        btnKitServico1.setToolTipText("Relatórios de produtos e serviços");
        btnKitServico1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnKitServico1.addActionListener(this::btnKitServico1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCadCliente)
                    .addComponent(btnCadProd)
                    .addComponent(btnCadForn)
                    .addComponent(btnCadFunc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgenda)
                    .addComponent(btnRelatorios)
                    .addComponent(btnKitServico)
                    .addComponent(btnKitServico1))
                .addGap(97, 97, 97))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSair)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAgenda)
                                .addGap(18, 18, 18)
                                .addComponent(btnRelatorios))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCadCliente)
                                .addGap(18, 18, 18)
                                .addComponent(btnCadForn)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKitServico)
                    .addComponent(btnCadProd))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKitServico1)
                    .addComponent(btnCadFunc))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed

        System.exit(0);

    }//GEN-LAST:event_btnSairActionPerformed

    private void btnCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadClienteActionPerformed

        CadastroCliente cadCli = new CadastroCliente(this.usuarioLogado);
        cadCli.setLocationRelativeTo(this);
        cadCli.setVisible(true);

    }//GEN-LAST:event_btnCadClienteActionPerformed

    private void btnCadFornActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadFornActionPerformed

        CadastroFornecedor cadForn = new CadastroFornecedor(this.usuarioLogado);
        cadForn.setLocationRelativeTo(this);
        cadForn.setVisible(true);


    }//GEN-LAST:event_btnCadFornActionPerformed

    private void btnCadProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadProdActionPerformed

        CadastroProduto cadProd = new CadastroProduto(this.usuarioLogado);
        cadProd.setLocationRelativeTo(this);
        cadProd.setVisible(true);

    }//GEN-LAST:event_btnCadProdActionPerformed

    private void btnCadFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadFuncActionPerformed

        CadastroFuncionario cadastrar = new CadastroFuncionario(this.usuarioLogado);
        cadastrar.setLocationRelativeTo(this);
        cadastrar.setVisible(true);

    }//GEN-LAST:event_btnCadFuncActionPerformed

    private void btnAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendaActionPerformed

        TelaAgenda cadAgenda = new TelaAgenda(this.usuarioLogado);
        cadAgenda.setLocationRelativeTo(this);
        cadAgenda.setVisible(true);

    }//GEN-LAST:event_btnAgendaActionPerformed

    private void btnRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatoriosActionPerformed
        TelaRelatorio telaRel = new TelaRelatorio(this.usuarioLogado);
        telaRel.setLocationRelativeTo(this);
        telaRel.setVisible(true);

    }//GEN-LAST:event_btnRelatoriosActionPerformed

    private void btnKitServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKitServicoActionPerformed

        CadastroServico cadServico = new CadastroServico(this.usuarioLogado);
        cadServico.setLocationRelativeTo(this);
        cadServico.setVisible(true);

    }//GEN-LAST:event_btnKitServicoActionPerformed

    private void btnKitServico1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKitServico1ActionPerformed

        CadastroKitServico cadKit = new CadastroKitServico(this.usuarioLogado);
        cadKit.setLocationRelativeTo(this);
        cadKit.setVisible(true);

    }//GEN-LAST:event_btnKitServico1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaInicial(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgenda;
    private javax.swing.JButton btnCadCliente;
    private javax.swing.JButton btnCadForn;
    private javax.swing.JButton btnCadFunc;
    private javax.swing.JButton btnCadProd;
    private javax.swing.JButton btnKitServico;
    private javax.swing.JButton btnKitServico1;
    private javax.swing.JButton btnRelatorios;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
