package view;

public class TelaRelatorio extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaRelatorio.class.getName());
    private model.Usuario usuarioLogado;

    public TelaRelatorio(model.Usuario usuario) {
        this.usuarioLogado = usuario;
        initComponents();

        verificarPermissoes();
    }

    private void verificarPermissoes() {

        if (!usuarioLogado.getPerfil().equalsIgnoreCase("gerente")) {

            btnRelatorioDeLog.setVisible(false);
            btnRelatorioBackup.setVisible(false);

            System.out.println("Acesso restrito aplicado para o perfil: " + usuarioLogado.getPerfil());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRelatorioBackup = new javax.swing.JButton();
        btnRelatorioDeLog = new javax.swing.JButton();
        btnEstoque = new javax.swing.JButton();
        btnVoltarTelaInicial = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Relatórios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 36)); // NOI18N
        jLabel1.setText("Instituto da Beleza");

        btnRelatorioBackup.setBackground(new java.awt.Color(255, 255, 0));
        btnRelatorioBackup.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRelatorioBackup.setText("Relatório de backup");
        btnRelatorioBackup.setToolTipText("Salários e pagamentos");
        btnRelatorioBackup.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRelatorioBackup.addActionListener(this::btnRelatorioBackupActionPerformed);

        btnRelatorioDeLog.setBackground(new java.awt.Color(255, 255, 0));
        btnRelatorioDeLog.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRelatorioDeLog.setText("Relatório de logs");
        btnRelatorioDeLog.setToolTipText("Pagamentos feitos e recebidos");
        btnRelatorioDeLog.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRelatorioDeLog.addActionListener(this::btnRelatorioDeLogActionPerformed);

        btnEstoque.setBackground(new java.awt.Color(255, 255, 0));
        btnEstoque.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEstoque.setText("Relatório de Estoque");
        btnEstoque.setToolTipText("Controle de estoque");
        btnEstoque.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEstoque.addActionListener(this::btnEstoqueActionPerformed);

        btnVoltarTelaInicial.setBackground(new java.awt.Color(255, 255, 0));
        btnVoltarTelaInicial.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVoltarTelaInicial.setText("Voltar");
        btnVoltarTelaInicial.setToolTipText("Volta para a tela inicial");
        btnVoltarTelaInicial.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVoltarTelaInicial.addActionListener(this::btnVoltarTelaInicialActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRelatorioBackup)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEstoque)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRelatorioDeLog)
                        .addGap(18, 272, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnVoltarTelaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRelatorioDeLog)
                .addGap(35, 35, 35)
                .addComponent(btnEstoque)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnRelatorioBackup)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVoltarTelaInicial)
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarTelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarTelaInicialActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarTelaInicialActionPerformed

    private void btnRelatorioDeLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioDeLogActionPerformed

        TelaRelatorioLogs telaLogs = new TelaRelatorioLogs(this.usuarioLogado);
        telaLogs.setLocationRelativeTo(this);
        telaLogs.setVisible(true);

    }//GEN-LAST:event_btnRelatorioDeLogActionPerformed

    private void btnEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstoqueActionPerformed

        TelaRelatorioEstoque telaEstoque = new TelaRelatorioEstoque(this.usuarioLogado);
        telaEstoque.setLocationRelativeTo(this);
        telaEstoque.setVisible(true);

    }//GEN-LAST:event_btnEstoqueActionPerformed

    private void btnRelatorioBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioBackupActionPerformed

        TelaRelatorioBackups telaBackup = new TelaRelatorioBackups(this.usuarioLogado);
        telaBackup.setLocationRelativeTo(this);
        telaBackup.setVisible(true);

    }//GEN-LAST:event_btnRelatorioBackupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaRelatorio(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEstoque;
    private javax.swing.JButton btnRelatorioBackup;
    private javax.swing.JButton btnRelatorioDeLog;
    private javax.swing.JButton btnVoltarTelaInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
